-- Seed: Wahrheit oder Pflicht (spice 1 = harmlos, 2 = würzig, 3 = heiß)

insert into public.td_prompts (kind, text, spice) values
-- ===== WAHRHEIT =====
('truth', 'Was war dein peinlichster Moment in der Schule?', 1),
('truth', 'Welche App auf deinem Handy würdest du niemandem zeigen wollen?', 1),
('truth', 'Was war die größte Lüge, die du je erzählt hast?', 2),
('truth', 'Wen in dieser Runde kanntest du als erstes – und was war dein erster Eindruck?', 1),
('truth', 'Was ist dein heimliches Guilty Pleasure?', 1),
('truth', 'Hast du schon mal etwas gestohlen? Was?', 2),
('truth', 'Was ist das Kindischste, das du immer noch tust?', 1),
('truth', 'Welche Nachricht in deinem Handy würde dich am meisten blamieren?', 2),
('truth', 'Was war dein schlimmstes Date?', 2),
('truth', 'Hast du schon mal jemanden geghostet? Warum?', 2),
('truth', 'Was ist deine unbeliebteste Meinung, zu der du trotzdem stehst?', 1),
('truth', 'Wann hast du das letzte Mal geweint und warum?', 2),
('truth', 'Was war das Teuerste, das du je kaputt gemacht hast – und hast du es zugegeben?', 1),
('truth', 'Welchen Promi findest du heimlich attraktiv, obwohl es dir peinlich ist?', 1),
('truth', 'Was würdest du tun, wenn du einen Tag unsichtbar wärst?', 1),
('truth', 'Hast du schon mal bei einem Spiel betrogen? Bei welchem?', 1),
('truth', 'Welche Angewohnheit von dir nervt andere am meisten?', 1),
('truth', 'Was ist das Verrückteste, das du je für einen Crush getan hast?', 2),
('truth', 'Hast du schon mal so getan, als wärst du krank, um etwas abzusagen?', 1),
('truth', 'Was ist dein größter Irrglaube gewesen, an den du viel zu lange geglaubt hast?', 1),
('truth', 'Welches Geheimnis hast du am längsten für dich behalten?', 3),
('truth', 'Wen aus dieser Runde würdest du anrufen, wenn du eine Leiche verstecken müsstest?', 1),
('truth', 'Was war dein schlechtester Kauf aller Zeiten?', 1),
('truth', 'Hast du schon mal heimlich das Handy von jemand anderem durchsucht?', 2),
('truth', 'Was ist das Peinlichste in deinem Suchverlauf?', 2),
('truth', 'Über wen in dieser Runde hast du dir schon mal Gedanken gemacht, die du nie laut sagen würdest?', 3),
('truth', 'Was ist die kindischste Sache, wegen der du dich je gestritten hast?', 1),
('truth', 'Hast du schon mal etwas kaputt gemacht und jemand anderen beschuldigt?', 2),
('truth', 'Was war der mutigste Moment deines Lebens?', 1),
('truth', 'Welche Lüge erzählst du am häufigsten?', 2),
('truth', 'Was würdest du an deinem Aussehen ändern, wenn du könntest?', 2),
('truth', 'Was war das Schlimmste, das du je über einen Lehrer oder Chef gesagt hast?', 2),
('truth', 'Hast du schon mal jemanden aus dieser Runde bei anderen schlecht geredet?', 3),
('truth', 'Welches Kompliment hättest du gern öfter?', 1),
('truth', 'Was ist deine größte irrationale Angst?', 1),
('truth', 'Wie lange warst du maximal ungeduscht?', 2),
('truth', 'Hast du schon mal Essen aus dem Müll gegessen?', 2),
('truth', 'Was war dein peinlichster Moment vor fremden Leuten?', 1),
('truth', 'Welchen Spitznamen hattest du als Kind, den niemand kennen soll?', 1),
('truth', 'Was ist das Längste, das du je durchgehend gezockt oder Serien geschaut hast?', 1),
('truth', 'Hast du schon mal einen Liebesbrief geschrieben? An wen?', 2),
('truth', 'Was ist dein größtes finanzielles Geheimnis?', 2),
('truth', 'Welche Entscheidung bereust du am meisten?', 2),
('truth', 'Was würden deine Eltern niemals über dich erfahren dürfen?', 3),
('truth', 'Hast du schon mal jemanden geküsst, den du nicht hättest küssen sollen?', 3),
('truth', 'Was ist das Seltsamste, das du je gegessen hast?', 1),
('truth', 'Wie oft stalkst du Ex-Partner oder alte Crushes in sozialen Medien?', 2),
('truth', 'Was war die schlechteste Note deines Lebens und wie kam es dazu?', 1),
('truth', 'Welches Talent hättest du gerne, das du absolut nicht hast?', 1),
('truth', 'Was ist der unnötigste Gegenstand, den du besitzt?', 1),
('truth', 'Hast du schon mal etwas im Laden kaputt gemacht und bist einfach gegangen?', 2),
('truth', 'Was ist dein Red Flag, die du selbst zugibst?', 2),
('truth', 'Auf welche Nachricht wartest du gerade insgeheim?', 2),
('truth', 'Welche Serie oder welchen Film schaust du heimlich, obwohl er nicht zu dir passt?', 1),
('truth', 'Was war dein peinlichster Auftritt vor Publikum?', 1),
('truth', 'Hast du schon mal einen Tag komplett im Bett verbracht? Wann zuletzt?', 1),
('truth', 'Welchen Menschen vermisst du am meisten?', 2),
('truth', 'Was ist das Netteste, das je jemand für dich getan hat?', 1),
('truth', 'Bei welcher Kleinigkeit wirst du sofort wütend?', 1),
('truth', 'Was ist dein peinlichster Ohrwurm aller Zeiten?', 1),
('truth', 'Hast du schon mal so getan, als würdest du jemanden nicht sehen, um nicht zu grüßen?', 1),
('truth', 'Welche Doppelmoral lebst du selbst?', 2),
('truth', 'Was war das Riskanteste, das du je gemacht hast?', 2),
('truth', 'Welcher Moment deines Lebens würde als Serien-Folge am besten funktionieren?', 1),
('truth', 'Wem aus dieser Runde würdest du dein Handy entsperrt für eine Stunde geben – und wem niemals?', 2),
('truth', 'Was hast du als Kind angestellt, ohne dass es je aufgeflogen ist?', 2),
('truth', 'Welches Gerücht über dich hat dich am meisten geärgert?', 2),
('truth', 'Was ist deine schlechteste Angewohnheit beim Essen?', 1),
('truth', 'Wie viele Selfies machst du, bevor du eins postest?', 1),
('truth', 'Was war dein peinlichster Autokorrektur-Fail?', 1),
('truth', 'Für welchen Promi würdest du alles stehen und liegen lassen?', 1),
('truth', 'Was ist das Spontanste, das du je gemacht hast?', 1),
('truth', 'Welche Ausrede benutzt du am häufigsten, um Pläne abzusagen?', 1),
('truth', 'Was würdest du mit einer Million Euro als Erstes machen?', 1),
('truth', 'Welcher Song beschreibt dein Leben gerade am besten?', 1),
('truth', 'Was ist dein größter Beauty- oder Style-Fail gewesen?', 1),
('truth', 'Hast du schon mal an einem Ort übernachtet, an dem du nicht hättest sein dürfen?', 2),
('truth', 'Was ist das Peinlichste, das deine Eltern je vor anderen über dich erzählt haben?', 1),
('truth', 'Wen würdest du aus dieser Runde mit auf eine einsame Insel nehmen und warum?', 1),
('truth', 'Welches Thema googelst du ständig, obwohl du es niemandem erzählst?', 2),
('truth', 'Was war dein bester Schultrick, um nicht dranzukommen?', 1),
('truth', 'Welcher Mensch hat dich am meisten enttäuscht?', 3),
('truth', 'Was ist das Schönste, das dir je jemand gesagt hat?', 1),
('truth', 'Hast du schon mal etwas zurück in den Laden gebracht, das du selbst kaputt gemacht hast?', 2),
('truth', 'Wie sieht dein Browser-Tab-Chaos gerade aus – wie viele sind offen?', 1),
('truth', 'Was ist die teuerste Sache, die du je verloren hast?', 1),
('truth', 'Welche Phase deines Lebens würdest du nie wieder durchmachen wollen?', 2),
('truth', 'Was hast du zuletzt heimlich gefeiert, das eigentlich schlecht für jemand anderen war?', 3),
('truth', 'Welches Foto auf deinem Handy müsste sofort gelöscht werden, wenn jemand es findet?', 3),
('truth', 'Was ist dein bisher größter "Fake it till you make it"-Moment gewesen?', 1),
('truth', 'Wie viele Leute in dieser Runde hast du schon mal auf Social Media gestalkt?', 2),
('truth', 'Was würdest du tun, wenn du wüsstest, dass es niemand je erfährt?', 3),
('truth', 'Welcher kleine Erfolg hat dich zuletzt richtig stolz gemacht?', 1),
('truth', 'Was war das Unangenehmste, das dir je beim Sport passiert ist?', 1),
('truth', 'Welche Trend-Sache hast du mitgemacht und bereust es heute?', 1),
('truth', 'Wann hast du das letzte Mal so richtig herzhaft gelacht und worüber?', 1),
('truth', 'Welche Regel deiner Eltern hast du am häufigsten gebrochen?', 1),
('truth', 'Was würdest du tun, wenn du für einen Tag das andere Geschlecht hättest?', 2),
('truth', 'Wie lange würdest du es ohne Handy aushalten – ehrlich?', 1),
('truth', 'Was war dein peinlichster Versprecher aller Zeiten?', 1),
('truth', 'Welchen Beruf hättest du in einem anderen Leben gewählt?', 1),
('truth', 'Was ist das Merkwürdigste, das du je gesammelt hast?', 1),
('truth', 'Welche Eigenschaft hättest du gern von der Person rechts von dir?', 1),
('truth', 'Was war das letzte, worüber du dich tierisch aufgeregt hast – und war es das wert?', 1),
('truth', 'Hast du schon mal absichtlich verloren, damit jemand anderes gewinnt?', 1),
('truth', 'Welcher Geruch katapultiert dich sofort in deine Kindheit?', 1),
('truth', 'Was ist der unnötigste Streit, den du je geführt hast?', 1),
('truth', 'Welches Klischee über dich stimmt zu 100 Prozent?', 1),

-- ===== PFLICHT =====
('dare', 'Imitiere eine Person aus der Runde, bis jemand errät, wer es ist.', 1),
('dare', 'Sprich die nächsten 3 Runden in einem Akzent deiner Wahl.', 1),
('dare', 'Zeig das letzte Foto in deiner Galerie und erkläre es.', 2),
('dare', 'Tanze 30 Sekunden ohne Musik.', 1),
('dare', 'Lass die Gruppe eine Nachricht an einen Kontakt deiner Wahl aus deinem Handy schicken (Gruppe entscheidet den Text, du das Opfer).', 3),
('dare', 'Sing den Refrain deines Lieblingssongs, so laut du dich traust.', 1),
('dare', 'Mach 15 Liegestütze oder 30 Hampelmänner.', 1),
('dare', 'Erzähle einen Witz – wenn keiner lacht, musst du noch einen erzählen.', 1),
('dare', 'Sprich bis zu deinem nächsten Zug nur in Reimen.', 1),
('dare', 'Lass dir von der Person links von dir eine neue Frisur machen.', 2),
('dare', 'Iss einen Löffel von einer Gewürz-Kombi, die die Gruppe zusammenstellt (essbar & harmlos!).', 2),
('dare', 'Poste ein von der Gruppe gewähltes Emoji als Status/Story – ohne Kontext.', 2),
('dare', 'Mach der Person gegenüber ein ernst gemeintes Kompliment – 20 Sekunden lang, ohne zu lachen.', 1),
('dare', 'Sprich eine Minute lang wie ein Nachrichtensprecher über das, was gerade im Raum passiert.', 1),
('dare', 'Lass dein Handy bis zum Ende des Spiels in der Mitte liegen – Benachrichtigungen sichtbar.', 2),
('dare', 'Stell dein peinlichstes Kindheitsfoto in die Gruppe (falls verfügbar).', 2),
('dare', 'Mach eine Modenschau mit dem Kleidungsstück, das dir die Gruppe gibt.', 1),
('dare', 'Versuche eine Minute lang nicht zu blinzeln, während dich alle anstarren.', 1),
('dare', 'Lies die letzte Sprachnachricht laut vor, die du verschickt hast (oder spiel sie ab).', 3),
('dare', 'Sprich bis zu deinem nächsten Zug jeden Satz mit "Euer Ehren" am Ende.', 1),
('dare', 'Lass dich von der Gruppe 60 Sekunden lang interviewen – du musst auf alles antworten (oder trinken/Punkt abgeben).', 2),
('dare', 'Mach den Tier-Laut, den dir die Gruppe nennt – 3 Mal, mit vollem Einsatz.', 1),
('dare', 'Balanciere einen Gegenstand deiner Wahl 30 Sekunden auf dem Kopf.', 1),
('dare', 'Erzähl die Handlung deines Lieblingsfilms in genau 10 Sekunden.', 1),
('dare', 'Tausch ein Kleidungsstück mit der Person rechts von dir für 3 Runden.', 2),
('dare', 'Schreib mit geschlossenen Augen eine Nachricht und schick sie an einen von der Gruppe gewählten Chat – so wie sie ist.', 3),
('dare', 'Mach 30 Sekunden lang Werbung für den Gegenstand links von dir, als wäre es Teleshopping.', 1),
('dare', 'Lauf einmal wie ein Pinguin durch den Raum.', 1),
('dare', 'Sprich 2 Runden lang nur in Flüsterton – egal was passiert.', 1),
('dare', 'Zeig der Gruppe deinen Bildschirmzeit-Report dieser Woche.', 2),
('dare', 'Lass die Person gegenüber 3 Fragen stellen, die du nur mit Ja oder Nein beantworten darfst.', 2),
('dare', 'Erfinde spontan einen 20-sekündigen Rap über die Person, die links von dir sitzt.', 1),
('dare', 'Iss oder trink etwas, das zwei andere Spieler für dich kombinieren (essbar!).', 2),
('dare', 'Stell dich hin und halte eine 30-sekündige Dankesrede, als hättest du einen Oscar gewonnen.', 1),
('dare', 'Mach ein Selfie mit der dämlichsten Grimasse und lass es die Gruppe als dein neues Gruppenbild festlegen.', 2),
('dare', 'Versuch, eine Minute lang mit der Zunge deine Nase zu berühren – immer wieder.', 1),
('dare', 'Sag das Alphabet rückwärts auf – bei jedem Fehler von vorn (max. 3 Versuche).', 1),
('dare', 'Gib deinem Sitznachbarn eine 30-sekündige Schultermassage.', 1),
('dare', 'Sprich deinen nächsten Satz singend in Opern-Manier.', 1),
('dare', 'Zeig die 5 zuletzt verwendeten Emojis auf deiner Tastatur.', 1),
('dare', 'Erkläre 30 Sekunden lang ein ernstes Thema, während alle versuchen, dich zum Lachen zu bringen.', 1),
('dare', 'Mach den "Roboter-Tanz", bis deine nächste Runde beginnt.', 1),
('dare', 'Lies den letzten Chat-Verlauf mit deiner Mutter mit verteilten Rollen vor (du spielst beide).', 2),
('dare', 'Tu für 2 Runden so, als wärst du der Butler der Gruppe – inklusive Getränkeservice.', 1),
('dare', 'Lass dir die Augen verbinden und errate 3 Gegenstände nur durch Ertasten.', 1),
('dare', 'Erzähl die peinlichste Geschichte über dich selbst, die dir einfällt – in 30 Sekunden.', 2),
('dare', 'Sag jedem in der Runde eine Sache, die du an ihm oder ihr bewunderst.', 1),
('dare', 'Versuch eine Minute zu planken, während die Gruppe dir Fragen stellt.', 1),
('dare', 'Mach das Geräusch deines Klingeltons mit dem Mund nach.', 1),
('dare', 'Sprich bis zum Ende der Runde jeden in der Runde nur mit "Eure Majestät" an.', 1),
('dare', 'Lass die Gruppe deinen neuen Insta-/WhatsApp-Profilnamen für 24 Stunden bestimmen.', 3),
('dare', 'Stell die erste Szene eines Films pantomimisch dar, bis jemand ihn errät.', 1),
('dare', 'Mach mit geschlossenen Augen ein Porträt der Person gegenüber (Stift & Papier oder Handy).', 1),
('dare', 'Erzähl in 20 Sekunden, warum du das beste Mitglied dieser Gruppe bist – mit voller Überzeugung.', 1),
('dare', 'Lass dich von der Gruppe für den Rest des Spiels mit einem neuen Spitznamen ansprechen, den sie sich ausdenken.', 1),
('dare', 'Iss eine Zitrone-/saure Scheibe ohne Grimasse (falls vorhanden) – oder halte 30 Sekunden Eiswasser-Kontakt aus.', 2),
('dare', 'Spiel 30 Sekunden Luftgitarre mit vollem Körpereinsatz.', 1),
('dare', 'Telefoniere mit einer Person deiner Wahl und bring "Ananas", "U-Boot" und "Tante Erna" im Gespräch unter.', 3),
('dare', 'Mach 3 Runden lang nach jedem deiner Sätze einen Trommelwirbel auf dem Tisch.', 1),
('dare', 'Stell dich 30 Sekunden in die Ecke und denk "über dein Verhalten nach", während alle weiterspielen.', 1),
('dare', 'Sag der Person gegenüber mit todernstem Blick: "Wir müssen reden." und halte 10 Sekunden Blickkontakt.', 1),
('dare', 'Zieh deine Socken aus und trag sie für 2 Runden an den Händen.', 1),
('dare', 'Beschreibe dein letztes Date / deinen letzten Schwarm in 3 Worten.', 2),
('dare', 'Lass jemanden aus der Gruppe 30 Sekunden lang in deinem Handy scrollen (App ihrer Wahl, nur gucken).', 3),
('dare', 'Sprich für eine Runde nur in der dritten Person über dich selbst.', 1),
('dare', 'Stell den Sonnenuntergang pantomimisch dar. Die Gruppe bewertet mit Punktetafeln.', 1),
('dare', 'Erfinde eine neue Begrüßung mit Handschlag-Choreo und bring sie zwei Leuten bei.', 1),
('dare', 'Flüstere der Person links von dir ein Geheimnis ins Ohr (sie darf es nicht verraten).', 2),
('dare', 'Mach einen Handstand oder den Versuch davon (an der Wand erlaubt).', 1),
('dare', 'Gähne so lange ansteckend, bis mindestens zwei andere auch gähnen.', 1),
('dare', 'Sag 10 Mal schnell hintereinander "Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid".', 1),
('dare', 'Lös in 60 Sekunden so viele Kopfrechenaufgaben, wie die Gruppe dir stellt – pro Fehler ein Frosch-Hüpfer.', 1),
('dare', 'Trink ein Glas Wasser in einem Zug (oder iss einen Cracker ohne etwas zu trinken und pfeife danach).', 1),
('dare', 'Lass dir von der Gruppe drei Wörter geben und baue sie unauffällig in deine nächsten drei Sätze ein.', 1),
('dare', 'Zeig deinen Browserverlauf von heute (nur den heutigen Tag!).', 3),
('dare', 'Beende jede deiner Aussagen bis zu deinem nächsten Zug mit "…aber das bleibt unter uns."', 1),
('dare', 'Spiel eine Szene: Du bist Wetterfee/Wettermann und kündigst das Wetter von morgen dramatisch an.', 1),
('dare', 'Halte einen 30-sekündigen Vortrag über ein Thema, das die Gruppe wählt – als absoluter Experte.', 1),
('dare', 'Mach deinem Spiegelbild (oder der Frontkamera) ernsthaft ein Date-Angebot.', 2),
('dare', 'Lass dich 3 Runden lang von der Gruppe fernsteuern: Sitzposition, Gestik, Mimik.', 2),
('dare', 'Schreib "Ich habe eine wichtige Ankündigung" in einen Gruppenchat deiner Wahl und antworte 10 Minuten nicht.', 3),
('dare', 'Zeichne in 30 Sekunden ein Porträt der Person gegenüber mit deiner schwachen Hand.', 1),
('dare', 'Versuch, 20 Sekunden lang auf einem Bein zu stehen – mit geschlossenen Augen.', 1),
('dare', 'Sprich deinen nächsten Wortbeitrag wie ein Fußballkommentator, der ein Tor ankündigt.', 1),
('dare', 'Erzähl der Gruppe von deinem letzten Traum, an den du dich erinnerst – ungefiltert.', 2),
('dare', 'Lass die Person rechts von dir dein nächstes Profilbild aus den Fotos auf deinem Handy aussuchen.', 3),
('dare', 'Mach 10 Kniebeugen und zähle dabei laut auf einer anderen Sprache (notfalls Fantasiesprache).', 1),
('dare', 'Tu so, als würdest du in Zeitlupe niesen – volle 15 Sekunden.', 1),
('dare', 'Sag den Satz "Ich bin ein kleiner Teekessel" in 5 verschiedenen Emotionen.', 1),
('dare', 'Lass dir vom Rest der Gruppe eine Aufgabe geben, die du innerhalb der nächsten Stunde erfüllen musst.', 2),
('dare', 'Versuch ohne Hände aufzustehen und dich wieder zu setzen – 3 Mal.', 1),
('dare', 'Imitiere einen Influencer, der das Getränk auf dem Tisch promotet.', 1),
('dare', 'Sing "Happy Birthday" für die Person, die als nächstes Geburtstag hat – in Metal-Version.', 1),
('dare', 'Lass dir von der Gruppe eine Pose geben und friere 30 Sekunden darin ein.', 1),
('dare', 'Wähle: Erzähl ein Geheimnis ODER iss eine von der Gruppe gewählte (essbare) Kombination.', 3),
('dare', 'Sprich bis zu deinem nächsten Zug wie ein Pirat, inklusive "Arrr".', 1),
('dare', 'Mach ein dramatisches Foto-Shooting: 5 Posen in 15 Sekunden, die Gruppe fotografiert.', 1),
('dare', 'Erkläre der Gruppe Schritt für Schritt, wie man Zähne putzt – als wäre es eine epische Heldensage.', 1),
('dare', 'Stell dich vor die Gruppe und erzähl 30 Sekunden lang NUR positive Dinge über dich – ohne Lachen.', 1),
('dare', 'Tausche für eine Runde den Platz und die Identität mit der Person gegenüber – antworte als sie.', 1),
('dare', 'Mach das beste Babygesicht, das du kannst, und halte es 20 Sekunden.', 1),
('dare', 'Beschreibe deinen perfekten Tag in genau 15 Sekunden – Stoppuhr läuft.', 1),
('dare', 'Lauf rückwärts durch den Raum und kommentiere dich dabei selbst wie ein Sportreporter.', 1),
('dare', 'Halte die Hand der Person neben dir für die komplette nächste Runde.', 2),
('dare', 'Erfinde einen geheimen Handschlag mit der Person gegenüber – Vorführung obligatorisch.', 1),
('dare', 'Tu 30 Sekunden so, als wärst du in einem stummen Schwarz-Weiß-Film gefangen.', 1),
('dare', 'Lies einen beliebigen Text vor, als wäre er die spannendste Krimi-Stelle aller Zeiten.', 1),
('dare', 'Mach jedem in der Runde nacheinander dein bestes Zwinker-Gesicht.', 1);
