-- Seed: Never Have I Ever ("Ich hab noch nie…")

insert into public.nhie_prompts (text, spice) values
('… einen ganzen Tag im Schlafanzug verbracht.', 1),
('… so getan, als hätte ich eine Nachricht nicht gesehen.', 1),
('… bei einer Prüfung gespickt.', 2),
('… jemandem ein Geschenk weitergeschenkt, das ich selbst bekommen habe.', 1),
('… ein ganzes Wochenende durchgehend eine Serie geschaut.', 1),
('… heimlich den Kühlschrank von Freunden geplündert.', 1),
('… eine Ausrede erfunden, um früher von einer Party zu gehen.', 1),
('… mit Absicht das WLAN ausgeschaltet, damit andere denken, es sei kaputt.', 1),
('… jemanden auf Social Media gestalkt, den ich nie getroffen habe.', 2),
('… einen Mitschüler oder Kollegen petzen lassen, obwohl ich es war.', 2),
('… in der Öffentlichkeit laut gesungen, als wäre niemand da.', 1),
('… einen Streich gespielt, der völlig nach hinten losging.', 1),
('… in einem Restaurant nach dem Probieren behauptet, es schmeckt – obwohl es furchtbar war.', 1),
('… vergessen, wie jemand heißt, während ich mit der Person geredet habe.', 1),
('… einen Film-Klassiker komplett vorgetäuscht gesehen zu haben.', 1),
('… absichtlich auf eine Nachricht erst Stunden später geantwortet, um cool zu wirken.', 2),
('… meine Eltern angelogen, wo ich übernachte.', 2),
('… bei Monopoly oder einem Brettspiel betrogen.', 1),
('… ein Selfie an einem unpassenden Ort gemacht.', 1),
('… in der Schule oder Arbeit geschlafen.', 1),
('… etwas online bestellt und beim Auspacken sofort bereut.', 1),
('… einen Schwarm aus Versehen geliked und sofort wieder entliked.', 2),
('… so getan, als würde ich Sport mögen, um jemanden zu beeindrucken.', 1),
('… den Geburtstag eines guten Freundes vergessen.', 1),
('… auf einer Hochzeit oder Feier zu viel gegessen, dass mir schlecht war.', 1),
('… an einem öffentlichen Ort hingefallen und so getan, als wäre nichts gewesen.', 1),
('… einen kompletten Tag nur Junkfood gegessen.', 1),
('… ein Buch nur wegen des Covers gekauft und nie gelesen.', 1),
('… ein Geheimnis ausgeplaudert, das ich versprochen hatte zu behalten.', 2),
('… nachts heimlich das Haus verlassen.', 2),
('… mich vor einer Spinne so erschreckt, dass ich geschrien habe.', 1),
('… mit dem Auto/Fahrrad einen Mini-Unfall gebaut und es niemandem erzählt.', 2),
('… so lange geschlafen, dass der halbe Tag vorbei war.', 1),
('… in einem Videocall heimlich etwas ganz anderes gemacht.', 1),
('… eine Diät am selben Tag wieder abgebrochen.', 1),
('… mir selbst eine Nachricht geschrieben, um beschäftigt zu wirken.', 1),
('… Klamotten gekauft, einmal getragen und zurückgegeben.', 2),
('… jemanden absichtlich gewinnen lassen.', 1),
('… einen Lehrer oder Chef nachgemacht – und wurde fast erwischt.', 1),
('… aus dem Lachen nicht mehr rausgekommen, obwohl es total unpassend war.', 1),
('… mich bei einem Horrorfilm so erschreckt, dass ich etwas verschüttet habe.', 1),
('… ein Kompliment bekommen und keine Ahnung gehabt, wie ich reagieren soll.', 1),
('… vergessen, ob ich die Haustür abgeschlossen habe, und bin zurückgegangen.', 1),
('… mir eine Fake-Verpflichtung ausgedacht, um Pläne abzusagen.', 1),
('… die Lyrics eines Songs jahrelang falsch gesungen.', 1),
('… in einer Umkleide festgesteckt, weil etwas nicht gepasst hat.', 1),
('… einen Brief oder eine Nachricht geschrieben und nie abgeschickt.', 1),
('… eine Pflanze sterben lassen und sie heimlich ersetzt.', 1),
('… bei "Wer wird Millionär" mitgeraten und alles falsch gehabt.', 1),
('… einen Tag lang niemandem geantwortet, einfach weil ich keine Lust hatte.', 1),
('… jemandem aus Höflichkeit zugestimmt, ohne zuzuhören.', 1),
('… meine Schuhgröße oder Körpergröße geschummelt.', 1),
('… in einem Aufzug auf alle Knöpfe gedrückt.', 1),
('… so getan, als wäre mein Akku leer, um ein Gespräch zu beenden.', 1),
('… einen Spitznamen bekommen, den ich gehasst habe.', 1),
('… heimlich das letzte Stück Kuchen/Pizza gegessen und es abgestritten.', 1),
('… mich im Urlaub komplett verlaufen.', 1),
('… ein Geschenk vor dem eigentlichen Termin heimlich ausgepackt.', 1),
('… auf einer Party jemanden mit dem falschen Namen angesprochen.', 1),
('… eine ganze Nacht durchgemacht und am nächsten Tag alles abgesagt.', 1),
('… etwas in der Mikrowelle explodieren lassen.', 1),
('… bei einem Gruppenprojekt fast nichts gemacht und trotzdem die Lorbeeren kassiert.', 2),
('… mit jemandem geflirtet, um etwas umsonst zu bekommen.', 2),
('… meinen Standort gefaked.', 2),
('… einen peinlichen Tanz auf einer Familienfeier hingelegt.', 1),
('… mich beim Vorbeigehen in einer Spiegelung bewundert.', 1),
('… eine Sprachnachricht angehört, bevor ich sie abgeschickt habe – mehr als dreimal.', 1),
('… ein Gericht bestellt, nur weil ich den Namen nicht aussprechen konnte, den ich eigentlich wollte.', 1),
('… einen Wecker 10 Mal gesnoozed.', 1),
('… ein Meme an die falsche Person geschickt.', 2),
('… meine Hausaufgaben/Aufgaben von jemand anderem abgeschrieben.', 1),
('… bei einem Spiel so wütend geworden, dass ich aufgehört habe.', 1),
('… mit vollem Mund "interessant" gesagt, um nicht antworten zu müssen.', 1),
('… jemandem ein Lied vorgespielt und dabei die ganze Zeit dessen Reaktion beobachtet.', 1),
('… mich für einen Promi-Crush geschämt.', 1),
('… eine Geburtstagstorte vor dem Geburtstag angeschnitten.', 1),
('… in einem Schwimmbad oder See etwas verloren, das ich nie wiedergefunden habe.', 1),
('… einen Tag im Bett verbracht und allen gesagt, ich sei beschäftigt.', 1),
('… mit jemandem aus dieser Runde ein Geheimnis geteilt, das die anderen nicht kennen.', 2),
('… so getan, als hätte ich einen Anruf, um einer Situation zu entkommen.', 1),
('… auf ein Date verzichtet, weil mir die Serie wichtiger war.', 1),
('… eine Lüge so lange erzählt, dass ich sie selbst fast geglaubt habe.', 2),
('… etwas repariert, indem ich einfach draufgehauen habe.', 1),
('… öffentlich geweint und so getan, als wäre es eine Allergie.', 1),
('… einen ganzen Geburtstag vergessen – meinen eigenen Beinahe-Termin eingeschlossen.', 1),
('… jemandem zugewunken, der gar nicht mich gemeint hat.', 1),
('… eine Tür gezogen, auf der groß "Drücken" stand.', 1),
('… beim Karaoke das Mikrofon nicht mehr hergegeben.', 1),
('… die Anzahl meiner gelesenen Bücher übertrieben.', 1),
('… einen Insider-Witz mitgelacht, den ich nicht verstanden habe.', 1),
('… mein Zimmer aufgeräumt, indem ich alles in einen Schrank gestopft habe.', 1),
('… mir vorgenommen, früh zu schlafen, und dann bis 3 Uhr gescrollt.', 1),
('… die Milch direkt aus der Packung getrunken.', 1),
('… vergessen, warum ich in einen Raum gegangen bin.', 1),
('… ein Foto 50 Mal gemacht, bis es "spontan" aussah.', 1),
('… bei einem Wettbewerb verloren und behauptet, ich hätte mich nicht angestrengt.', 1),
('… heimlich nachgeschaut, was ein Geschenk gekostet hat.', 1),
('… einen Film im Kino verschlafen.', 1),
('… meine Playlist für Gäste extra "cool" umgestellt.', 1),
('… ein Date gehabt, das so schlecht lief, dass ich es heute als Comedy erzähle.', 2),
('… jemanden geküsst und es sofort bereut.', 3),
('… einen Crush auf den Freund oder die Freundin eines Freundes gehabt.', 3),
('… ein Doppelleben auf Social Media geführt (Finsta, Zweitaccount…).', 2),
('… eine Beziehung beendet und am selben Abend gefeiert.', 3),
('… mich an einem Arbeitstag/Schultag krank gemeldet, obwohl ich fit war.', 2),
('… meine Ex/meinen Ex betrunken angerufen oder angeschrieben.', 3),
('… auf einer Party in etwas Fremdes reingeschnüffelt: fremder Kühlschrank, Badezimmerschrank…', 2),
('… so getan, als hätte ich Erfahrung in etwas, von dem ich null Ahnung hatte – im Bewerbungsgespräch.', 2),
('… etwas auf einer Party kaputt gemacht und es nie zugegeben.', 2),
('… zwei Dates an einem Tag gehabt.', 3),
('… jemanden nur wegen seines Essens/seiner Wohnung weiter getroffen.', 2),
('… eine ganze Torte/Pizza alleine gegessen.', 1),
('… in einem Club so getanzt, dass es Videobeweise gibt.', 2),
('… meine Followerzahl gecheckt, direkt nachdem jemand entfolgt ist.', 1),
('… ein Geheimnis nur erfahren, weil ich gelauscht habe.', 2),
('… nachts um 3 Uhr existenzielle Fragen gegoogelt.', 1),
('… so getan, als wäre ich fit, obwohl mich die Treppe fast besiegt hat.', 1),
('… im Urlaub so getan, als könnte ich die Landessprache.', 1),
('… bei einer Mutprobe gekniffen.', 1),
('… ein Konzert-Ticket gekauft und das Konzert verpennt.', 1),
('… in der falschen Stadt aus dem Zug/Bus gestiegen.', 1),
('… etwas Wichtiges in eine Spülmaschine, Waschmaschine oder Toilette fallen lassen.', 1),
('… eine Wette verloren und den Einsatz nie bezahlt.', 1),
('… meinen Internetverlauf gelöscht, kurz bevor jemand mein Handy bekam.', 2),
('… mir eingebildet, jemand winkt mir zu, und zurückgewunken.', 1),
('… auf eine Frage "Ja" gesagt, ohne sie verstanden zu haben – mit Konsequenzen.', 1),
('… eine Nacht woanders geschlafen und niemandem gesagt wo.', 3),
('… bei einem Familienessen unterm Tisch das Handy benutzt.', 1),
('… einen Trend mitgemacht, für den ich mich heute schäme.', 1);
