-- Seed: Quiz-Battle (Multiple Choice, correct = Index 0–3)

insert into public.quiz_questions (question, options, correct, category, difficulty) values
-- Geografie
('Welches ist das flächenmäßig größte Land der Erde?', '["Kanada","Russland","China","USA"]', 1, 'Geografie', 1),
('Wie heißt die Hauptstadt von Australien?', '["Sydney","Melbourne","Canberra","Perth"]', 2, 'Geografie', 2),
('Welcher Fluss fließt durch Paris?', '["Loire","Rhône","Seine","Garonne"]', 2, 'Geografie', 1),
('Wie viele Bundesländer hat Deutschland?', '["14","15","16","17"]', 2, 'Geografie', 1),
('Welcher Kontinent hat die meisten Länder?', '["Asien","Europa","Afrika","Südamerika"]', 2, 'Geografie', 2),
('Welches Land hat die Form eines Stiefels?', '["Spanien","Italien","Griechenland","Portugal"]', 1, 'Geografie', 1),
('Wie heißt der höchste Berg der Welt?', '["K2","Mount Everest","Kangchendzönga","Makalu"]', 1, 'Geografie', 1),
('Welcher Ozean ist der größte?', '["Atlantik","Indischer Ozean","Arktischer Ozean","Pazifik"]', 3, 'Geografie', 1),
('Die Hauptstadt von Kanada ist…', '["Toronto","Vancouver","Ottawa","Montreal"]', 2, 'Geografie', 2),
('Welches Land hat die meisten Einwohner?', '["China","USA","Indien","Indonesien"]', 2, 'Geografie', 2),
('In welchem Land liegt die Stadt Marrakesch?', '["Tunesien","Ägypten","Marokko","Algerien"]', 2, 'Geografie', 2),
('Welcher See ist der tiefste der Welt?', '["Bodensee","Baikalsee","Tanganjikasee","Kaspisches Meer"]', 1, 'Geografie', 2),
('Wie heißt die längste Gebirgskette der Welt?', '["Himalaya","Rocky Mountains","Anden","Alpen"]', 2, 'Geografie', 2),
('Welche Wüste ist die größte heiße Wüste der Erde?', '["Gobi","Sahara","Kalahari","Atacama"]', 1, 'Geografie', 1),
('Welche zwei Länder teilen sich die längste Grenze der Welt?', '["Russland & China","USA & Kanada","Chile & Argentinien","Indien & China"]', 1, 'Geografie', 2),
('Wie heißt die Hauptstadt der Schweiz?', '["Zürich","Genf","Bern","Basel"]', 2, 'Geografie', 1),
('Auf welchem Kontinent liegt der Kilimandscharo?', '["Asien","Südamerika","Afrika","Australien"]', 2, 'Geografie', 1),
('Welcher Staat der USA ist der flächenmäßig größte?', '["Texas","Kalifornien","Montana","Alaska"]', 3, 'Geografie', 2),

-- Geschichte
('In welchem Jahr fiel die Berliner Mauer?', '["1987","1989","1991","1993"]', 1, 'Geschichte', 1),
('Wer war der erste Mensch auf dem Mond?', '["Buzz Aldrin","Juri Gagarin","Neil Armstrong","Michael Collins"]', 2, 'Geschichte', 1),
('Welches Schiff sank 1912 auf seiner Jungfernfahrt?', '["Lusitania","Britannic","Titanic","Queen Mary"]', 2, 'Geschichte', 1),
('Wer malte die Mona Lisa?', '["Michelangelo","Leonardo da Vinci","Raffael","Botticelli"]', 1, 'Geschichte', 1),
('In welchem Jahr begann der Erste Weltkrieg?', '["1912","1914","1916","1918"]', 1, 'Geschichte', 1),
('Wie hieß der erste Bundeskanzler der Bundesrepublik Deutschland?', '["Willy Brandt","Konrad Adenauer","Ludwig Erhard","Helmut Schmidt"]', 1, 'Geschichte', 1),
('Welches antike Weltwunder stand in Ägypten?', '["Hängende Gärten","Koloss von Rhodos","Pyramiden von Gizeh","Zeus-Statue"]', 2, 'Geschichte', 1),
('Wer wurde 44 v. Chr. an den Iden des März ermordet?', '["Augustus","Julius Cäsar","Nero","Marcus Antonius"]', 1, 'Geschichte', 1),
('Welche Stadt war im antiken Griechenland für ihre Krieger bekannt?', '["Athen","Korinth","Sparta","Theben"]', 2, 'Geschichte', 1),
('Wann wurde die Bundesrepublik Deutschland gegründet?', '["1945","1947","1949","1951"]', 2, 'Geschichte', 2),
('Wer erfand den Buchdruck mit beweglichen Lettern in Europa?', '["Martin Luther","Johannes Gutenberg","Albrecht Dürer","Nikolaus Kopernikus"]', 1, 'Geschichte', 1),
('Welches Land schenkte den USA die Freiheitsstatue?', '["England","Spanien","Frankreich","Italien"]', 2, 'Geschichte', 1),
('Wie hieß die erste Frau im Weltall?', '["Sally Ride","Walentina Tereschkowa","Mae Jemison","Swetlana Sawizkaja"]', 1, 'Geschichte', 3),
('Welche Dynastie ließ die Verbotene Stadt in Peking errichten?', '["Han","Tang","Ming","Qing"]', 2, 'Geschichte', 3),
('In welchem Jahr endete der Zweite Weltkrieg in Europa?', '["1943","1944","1945","1946"]', 2, 'Geschichte', 1),
('Wer war Pharaonin von Ägypten und mit Cäsar sowie Marcus Antonius liiert?', '["Nofretete","Hatschepsut","Kleopatra","Isis"]', 2, 'Geschichte', 1),

-- Wissenschaft & Natur
('Wie viele Planeten hat unser Sonnensystem?', '["7","8","9","10"]', 1, 'Wissenschaft', 1),
('Was ist die chemische Formel von Wasser?', '["CO2","H2O","O2","H2O2"]', 1, 'Wissenschaft', 1),
('Welches Organ pumpt Blut durch den Körper?', '["Leber","Lunge","Herz","Niere"]', 2, 'Wissenschaft', 1),
('Wie schnell ist Licht ungefähr?', '["300.000 km/s","150.000 km/s","1.000 km/s","30.000 km/s"]', 0, 'Wissenschaft', 1),
('Welches Element hat das chemische Symbol "Au"?', '["Silber","Aluminium","Gold","Kupfer"]', 2, 'Wissenschaft', 1),
('Wie viele Knochen hat ein erwachsener Mensch ungefähr?', '["106","206","306","406"]', 1, 'Wissenschaft', 2),
('Welcher Planet ist der Sonne am nächsten?', '["Venus","Mars","Merkur","Erde"]', 2, 'Wissenschaft', 1),
('Was misst ein Seismograph?', '["Temperatur","Erdbeben","Luftdruck","Windgeschwindigkeit"]', 1, 'Wissenschaft', 1),
('Welches Gas atmen Pflanzen bei der Photosynthese ein?', '["Sauerstoff","Stickstoff","Kohlendioxid","Wasserstoff"]', 2, 'Wissenschaft', 1),
('Wer entwickelte die Relativitätstheorie?', '["Isaac Newton","Albert Einstein","Stephen Hawking","Max Planck"]', 1, 'Wissenschaft', 1),
('Wie nennt man Tiere, die sowohl Fleisch als auch Pflanzen fressen?', '["Karnivoren","Herbivoren","Omnivoren","Insektivoren"]', 2, 'Wissenschaft', 1),
('Welcher Planet wird "der rote Planet" genannt?', '["Jupiter","Venus","Saturn","Mars"]', 3, 'Wissenschaft', 1),
('Was ist der härteste natürliche Stoff der Erde?', '["Stahl","Granit","Diamant","Titan"]', 2, 'Wissenschaft', 1),
('Wie viel Prozent der Erdoberfläche sind ungefähr mit Wasser bedeckt?', '["50 %","60 %","70 %","80 %"]', 2, 'Wissenschaft', 1),
('Welches Teilchen hat eine negative Ladung?', '["Proton","Neutron","Elektron","Photon"]', 2, 'Wissenschaft', 1),
('Bei wie viel Grad Celsius kocht Wasser auf Meereshöhe?', '["90","95","100","110"]', 2, 'Wissenschaft', 1),
('Welche Blutgruppe gilt als Universalspender?', '["A","B","AB","0 negativ"]', 3, 'Wissenschaft', 2),
('Wie lange braucht das Licht der Sonne ungefähr bis zur Erde?', '["8 Sekunden","8 Minuten","8 Stunden","8 Tage"]', 1, 'Wissenschaft', 2),

-- Tiere
('Welches ist das größte Tier der Erde?', '["Afrikanischer Elefant","Blauwal","Giraffe","Pottwal"]', 1, 'Tiere', 1),
('Wie viele Beine hat eine Spinne?', '["6","8","10","12"]', 1, 'Tiere', 1),
('Welches Tier ist das schnellste Landtier?', '["Löwe","Antilope","Gepard","Windhund"]', 2, 'Tiere', 1),
('Welcher Vogel kann nicht fliegen?', '["Albatros","Pinguin","Falke","Möwe"]', 1, 'Tiere', 1),
('Wie nennt man ein junges Känguru?', '["Cub","Joey","Kit","Calf"]', 1, 'Tiere', 2),
('Welches Tier schläft im Stehen?', '["Hund","Katze","Pferd","Schwein"]', 2, 'Tiere', 1),
('Wie viele Herzen hat ein Oktopus?', '["1","2","3","4"]', 2, 'Tiere', 2),
('Welches Tier gilt als das giftigste Meerestier?', '["Steinfisch","Würfelqualle","Blauer Ringkrake","Seeschlange"]', 1, 'Tiere', 3),
('Was fressen Pandas hauptsächlich?', '["Eukalyptus","Bambus","Gras","Fisch"]', 1, 'Tiere', 1),
('Welches Tier kann seinen Kopf um fast 270 Grad drehen?', '["Adler","Eule","Papagei","Strauß"]', 1, 'Tiere', 1),
('Wie kommunizieren Bienen über Futterquellen?', '["Summen","Tanz","Duftspur","Flügelschlag"]', 1, 'Tiere', 2),
('Welches Säugetier kann fliegen?', '["Gleithörnchen","Fledermaus","Flugfisch","Lemur"]', 1, 'Tiere', 1),

-- Musik
('Wie viele Saiten hat eine klassische Gitarre?', '["4","5","6","7"]', 2, 'Musik', 1),
('Welche Band sang "Bohemian Rhapsody"?', '["The Beatles","Queen","Led Zeppelin","Pink Floyd"]', 1, 'Musik', 1),
('Wer ist der "King of Pop"?', '["Elvis Presley","Prince","Michael Jackson","Stevie Wonder"]', 2, 'Musik', 1),
('Aus welchem Land kommt die Band ABBA?', '["Norwegen","Dänemark","Schweden","Finnland"]', 2, 'Musik', 1),
('Welches Instrument hat 88 Tasten?', '["Orgel","Klavier","Akkordeon","Cembalo"]', 1, 'Musik', 1),
('Wer komponierte die 9. Sinfonie mit der "Ode an die Freude"?', '["Mozart","Bach","Beethoven","Haydn"]', 2, 'Musik', 1),
('Welche Sängerin wird "Queen B" genannt?', '["Rihanna","Beyoncé","Britney Spears","Billie Eilish"]', 1, 'Musik', 1),
('Wie heißt der größte Musikpreis der USA?', '["Oscar","Emmy","Grammy","Tony"]', 2, 'Musik', 1),
('Welcher DJ und Produzent stammt aus Schweden und starb 2018?', '["Tiësto","Avicii","David Guetta","Calvin Harris"]', 1, 'Musik', 2),
('Was bedeutet "a cappella"?', '["Sehr laut","Gesang ohne Instrumente","Sehr schnell","Mit Chor"]', 1, 'Musik', 1),
('Welche deutsche Band hatte mit "Du hast" internationalen Erfolg?', '["Die Toten Hosen","Rammstein","Scorpions","Kraftwerk"]', 1, 'Musik', 1),
('Mit welchem Song wurde Nena weltberühmt?', '["Irgendwie, irgendwo, irgendwann","99 Luftballons","Leuchtturm","Nur geträumt"]', 1, 'Musik', 1),

-- Film & TV
('Wie heißt der Zauberer in "Der Herr der Ringe"?', '["Dumbledore","Gandalf","Merlin","Saruman"]', 1, 'Film & TV', 1),
('Welcher Film gewann als erster Animationsfilm über 1 Milliarde Dollar?', '["Findet Nemo","Die Eiskönigin","Toy Story 3","Shrek 2"]', 2, 'Film & TV', 3),
('Wie heißt die Schule in "Harry Potter"?', '["Beauxbatons","Durmstrang","Hogwarts","Ilvermorny"]', 2, 'Film & TV', 1),
('Wer spielt Iron Man im Marvel-Universum?', '["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"]', 2, 'Film & TV', 1),
('In welcher Serie geht es um den Chemielehrer Walter White?', '["Better Call Saul","Breaking Bad","Ozark","Narcos"]', 1, 'Film & TV', 1),
('Wie heißt das fiktive afrikanische Land von Black Panther?', '["Zamunda","Wakanda","Genovia","Latveria"]', 1, 'Film & TV', 1),
('Welcher Hai-Film machte Steven Spielberg 1975 berühmt?', '["Deep Blue Sea","Der weiße Hai","Open Water","Sharknado"]', 1, 'Film & TV', 1),
('Wie heißen die gelben Helfer von Gru in "Ich – Einfach unverbesserlich"?', '["Mini-Mes","Minions","Mimics","Mites"]', 1, 'Film & TV', 1),
('Welche Serie spielt in Hawkins, Indiana?', '["Riverdale","Stranger Things","Dark","Twin Peaks"]', 1, 'Film & TV', 1),
('Wer ist Luke Skywalkers Vater?', '["Obi-Wan Kenobi","Darth Vader","Palpatine","Han Solo"]', 1, 'Film & TV', 1),
('Wie heißt der berühmteste Geheimagent mit der Nummer 007?', '["Jason Bourne","Ethan Hunt","James Bond","Jack Ryan"]', 2, 'Film & TV', 1),
('Welcher Streamingdienst produzierte "Squid Game"?', '["Amazon Prime","Disney+","Netflix","Apple TV+"]', 2, 'Film & TV', 1),
('In welchem Film sagt ein Computer namens HAL 9000 "I''m sorry, Dave"?', '["Blade Runner","2001: Odyssee im Weltraum","Alien","Interstellar"]', 1, 'Film & TV', 2),
('Wie heißt der Clownfisch in "Findet Nemo"?', '["Dorie","Marlin","Nemo","Crush"]', 2, 'Film & TV', 1),

-- Sport
('Wie viele Spieler stehen beim Fußball pro Team auf dem Platz?', '["9","10","11","12"]', 2, 'Sport', 1),
('Alle wie viele Jahre finden die Olympischen Sommerspiele statt?', '["2","3","4","5"]', 2, 'Sport', 1),
('In welchem Sport gibt es einen "Slam Dunk"?', '["Volleyball","Basketball","Handball","Tennis"]', 1, 'Sport', 1),
('Wie viele Grand-Slam-Turniere gibt es im Tennis pro Jahr?', '["3","4","5","6"]', 1, 'Sport', 1),
('Welches Land gewann die Fußball-WM 2014?', '["Brasilien","Argentinien","Deutschland","Spanien"]', 2, 'Sport', 1),
('Wie lang ist ein Marathon?', '["32,195 km","40,195 km","42,195 km","45,195 km"]', 2, 'Sport', 1),
('In welcher Sportart wird der Begriff "Birdie" verwendet?', '["Tennis","Golf","Cricket","Badminton"]', 1, 'Sport', 1),
('Wie viele Punkte gibt ein Touchdown im American Football?', '["3","6","7","8"]', 1, 'Sport', 2),
('Welche Farbe hat das Trikot des Führenden bei der Tour de France?', '["Grün","Rot","Gelb","Weiß"]', 2, 'Sport', 1),
('Wie viele Ringe hat das olympische Symbol?', '["4","5","6","7"]', 1, 'Sport', 1),
('Welcher Boxer nannte sich selbst "The Greatest"?', '["Mike Tyson","Muhammad Ali","George Foreman","Joe Frazier"]', 1, 'Sport', 1),
('Bei welchem Spielstand beginnt jedes Tennis-Spiel?', '["0:0 (Love all)","15:15","1:1","Einstand"]', 0, 'Sport', 1),

-- Essen & Trinken
('Aus welchem Land stammt die Pizza?', '["Frankreich","Griechenland","Italien","Spanien"]', 2, 'Essen & Trinken', 1),
('Was ist die Hauptzutat von Guacamole?', '["Tomate","Avocado","Paprika","Erbsen"]', 1, 'Essen & Trinken', 1),
('Welches Getreide wird für Sushi-Reis verwendet?', '["Langkornreis","Basmati","Rundkornreis","Wildreis"]', 2, 'Essen & Trinken', 2),
('Aus welchem Land kommt Sushi?', '["China","Thailand","Korea","Japan"]', 3, 'Essen & Trinken', 1),
('Was ist Tofu hauptsächlich?', '["Weizen","Soja","Reis","Mais"]', 1, 'Essen & Trinken', 1),
('Welche Frucht ist die Hauptzutat eines klassischen Smoothie-Bowls "Açaí"?', '["Mango","Açaí-Beere","Banane","Drachenfrucht"]', 1, 'Essen & Trinken', 1),
('Woraus wird traditioneller Hummus gemacht?', '["Linsen","Kichererbsen","Bohnen","Erbsen"]', 1, 'Essen & Trinken', 1),
('Welches Land ist der größte Kaffeeproduzent der Welt?', '["Kolumbien","Vietnam","Brasilien","Äthiopien"]', 2, 'Essen & Trinken', 2),
('Was macht Brot beim Backen aufgehen?', '["Salz","Hefe","Zucker","Mehl"]', 1, 'Essen & Trinken', 1),
('Welche Nudelsorte ist röhrenförmig?', '["Spaghetti","Penne","Tagliatelle","Linguine"]', 1, 'Essen & Trinken', 1),
('Welches Gewürz ist das teuerste der Welt?', '["Vanille","Kardamom","Safran","Trüffel"]', 2, 'Essen & Trinken', 1),
('Wie heißt das japanische Gericht aus gegrillten Hähnchenspießen?', '["Tempura","Yakitori","Ramen","Onigiri"]', 1, 'Essen & Trinken', 2),

-- Technik & Internet
('Wofür steht "WWW"?', '["World Wide Web","World Web Wide","Wide World Web","Web World Wide"]', 0, 'Technik', 1),
('Welche Firma entwickelte das iPhone?', '["Samsung","Google","Apple","Nokia"]', 2, 'Technik', 1),
('Was bedeutet "KI"?', '["Kern-Internet","Künstliche Intelligenz","Kabellose Infrastruktur","Kontrollierte Information"]', 1, 'Technik', 1),
('Wie hieß Google ursprünglich?', '["PageRank","BackRub","SearchIt","WebCrawl"]', 1, 'Technik', 3),
('Welcher Kurznachrichtendienst wurde in "X" umbenannt?', '["Instagram","Snapchat","Twitter","TikTok"]', 2, 'Technik', 1),
('Wer gründete Microsoft zusammen mit Paul Allen?', '["Steve Jobs","Bill Gates","Mark Zuckerberg","Elon Musk"]', 1, 'Technik', 1),
('Was misst man in "Mbit/s"?', '["Speicherplatz","Bildschirmauflösung","Datenübertragungsrate","Akku-Kapazität"]', 2, 'Technik', 1),
('In welchem Jahr wurde YouTube gegründet?', '["2003","2005","2007","2009"]', 1, 'Technik', 2),
('Welches Unternehmen entwickelt die PlayStation?', '["Microsoft","Nintendo","Sony","Sega"]', 2, 'Technik', 1),
('Was ist ein "Pixel"?', '["Ein Schriftzeichen","Ein Bildpunkt","Eine Speichereinheit","Ein Audioformat"]', 1, 'Technik', 1),

-- Allgemeinwissen
('Wie viele Minuten hat ein Tag?', '["1.440","1.420","1.460","1.400"]', 0, 'Allgemeinwissen', 2),
('Welche Farbe entsteht aus Blau und Gelb?', '["Orange","Grün","Lila","Braun"]', 1, 'Allgemeinwissen', 1),
('Wie viele Zähne hat ein erwachsener Mensch normalerweise (mit Weisheitszähnen)?', '["28","30","32","34"]', 2, 'Allgemeinwissen', 1),
('Welcher Monat hat 28 oder 29 Tage?', '["Januar","Februar","März","April"]', 1, 'Allgemeinwissen', 1),
('Wie nennt man ein Gedicht mit 14 Versen?', '["Ballade","Sonett","Haiku","Ode"]', 1, 'Allgemeinwissen', 2),
('Welche Währung wird in Japan verwendet?', '["Won","Yuan","Yen","Ringgit"]', 2, 'Allgemeinwissen', 1),
('Wie viele Streifen hat die Flagge der USA?', '["11","13","15","50"]', 1, 'Allgemeinwissen', 2),
('Was ist die meistgesprochene Muttersprache der Welt?', '["Englisch","Spanisch","Mandarin-Chinesisch","Hindi"]', 2, 'Allgemeinwissen', 1),
('Wie heißt die griechische Göttin des Sieges?', '["Athene","Nike","Hera","Artemis"]', 1, 'Allgemeinwissen', 1),
('Welches Sternzeichen folgt auf den Steinbock?', '["Schütze","Wassermann","Fische","Widder"]', 1, 'Allgemeinwissen', 2),
('Wie viele Buchstaben hat das deutsche Alphabet (ohne Umlaute und ß)?', '["24","25","26","27"]', 2, 'Allgemeinwissen', 1),
('Was sammelt ein Philatelist?', '["Münzen","Briefmarken","Schmetterlinge","Postkarten"]', 1, 'Allgemeinwissen', 1),
('Welcher Planet ist nach dem römischen Gott des Krieges benannt?', '["Jupiter","Merkur","Mars","Neptun"]', 2, 'Allgemeinwissen', 1),
('Wie nennt man die Angst vor engen Räumen?', '["Agoraphobie","Klaustrophobie","Arachnophobie","Akrophobie"]', 1, 'Allgemeinwissen', 1),
('Aus wie vielen Feldern besteht ein Schachbrett?', '["49","56","64","81"]', 2, 'Allgemeinwissen', 1),
('Welches ist das kleinste Land der Welt?', '["Monaco","San Marino","Vatikanstadt","Liechtenstein"]', 2, 'Allgemeinwissen', 1);
