-- Seed: Stadt Land Fluss Kategorien, Codenames-Wörter, Tabu-Wörter

-- ---------- Stadt Land Fluss ----------
insert into public.slf_categories (name) values
('Stadt'), ('Land'), ('Fluss'), ('Name'), ('Tier'), ('Beruf'),
('Essen'), ('Getränk'), ('Marke'), ('Promi'), ('Film/Serie'), ('Band/Musiker'),
('Pflanze'), ('Sportart'), ('Hobby'), ('Farbe'), ('Automarke'), ('Kleidungsstück'),
('Körperteil'), ('Schulfach'), ('Videospiel'), ('App'), ('Superheld'), ('Märchenfigur'),
('Etwas im Badezimmer'), ('Etwas in der Küche'), ('Etwas, das fliegt'), ('Etwas, das stinkt'),
('Grund zu spät zu kommen'), ('Sache auf einer Party'), ('Urlaubsziel'), ('Süßigkeit'),
('Obst/Gemüse'), ('Instrument'), ('Sprache'), ('Krankheit/Wehwehchen'), ('Werkzeug'),
('Möbelstück'), ('Jobs, die es bald nicht mehr gibt'), ('Ausrede fürs Nicht-Antworten'),
('Etwas Rundes'), ('Etwas Kaltes'), ('Disney-Figur'), ('Cocktail'), ('Emoji-Beschreibung');

-- ---------- Codenames ----------
insert into public.codenames_words (word) values
('Apfel'),('Anker'),('Adler'),('Ampel'),('Arzt'),('Auge'),('Bank'),('Bart'),('Batterie'),('Baum'),
('Berg'),('Bett'),('Biene'),('Bier'),('Blatt'),('Blitz'),('Bombe'),('Boot'),('Brief'),('Brille'),
('Brücke'),('Buch'),('Burg'),('Bus'),('Dach'),('Diamant'),('Dieb'),('Drache'),('Dusche'),('Ei'),
('Eis'),('Engel'),('Erde'),('Feder'),('Fenster'),('Feuer'),('Film'),('Fisch'),('Flasche'),('Flugzeug'),
('Fluss'),('Frosch'),('Fuchs'),('Gabel'),('Garten'),('Geist'),('Geld'),('Gericht'),('Gewitter'),('Gitarre'),
('Glas'),('Glocke'),('Gold'),('Grenze'),('Haar'),('Hafen'),('Hahn'),('Hai'),('Hammer'),('Hand'),
('Handy'),('Haus'),('Herz'),('Himmel'),('Honig'),('Hose'),('Hotel'),('Hund'),('Hut'),('Insel'),
('Jacke'),('Jäger'),('Kabel'),('Kaffee'),('Kamera'),('Kapitän'),('Karte'),('Katze'),('Kette'),('Kino'),
('Kirche'),('Kissen'),('Kiste'),('Klavier'),('Kleid'),('Knopf'),('Koch'),('Koffer'),('Komet'),('König'),
('Kopf'),('Krone'),('Küche'),('Kuchen'),('Kugel'),('Kuh'),('Künstler'),('Lampe'),('Land'),('Laser'),
('Lehrer'),('Leiter'),('Licht'),('Limo'),('Löffel'),('Löwe'),('Luft'),('Magnet'),('Mantel'),('Markt'),
('Maske'),('Mauer'),('Maus'),('Meer'),('Messer'),('Mond'),('Motor'),('Mücke'),('Mühle'),('Mund'),
('Münze'),('Musik'),('Nacht'),('Nadel'),('Nagel'),('Nase'),('Nebel'),('Nest'),('Netz'),('Oper'),
('Orange'),('Palast'),('Papier'),('Park'),('Party'),('Pferd'),('Pilot'),('Pilz'),('Pirat'),('Pizza'),
('Planet'),('Polizei'),('Post'),('Prinz'),('Puppe'),('Pyramide'),('Rad'),('Rakete'),('Regen'),('Reis'),
('Riese'),('Ring'),('Ritter'),('Roboter'),('Rose'),('Rücken'),('Sand'),('Schatten'),('Schatz'),('Schaf'),
('Schiff'),('Schild'),('Schlange'),('Schloss'),('Schlüssel'),('Schnee'),('Schokolade'),('Schule'),('Schwert'),('See'),
('Seife'),('Seil'),('Sessel'),('Socke'),('Sonne'),('Spiegel'),('Spinne'),('Sprache'),('Stadion'),('Stadt'),
('Stein'),('Stern'),('Stiefel'),('Strand'),('Straße'),('Strom'),('Stuhl'),('Sturm'),('Suppe'),('Tafel'),
('Tag'),('Tal'),('Tanz'),('Tasche'),('Tasse'),('Taube'),('Tee'),('Teppich'),('Theater'),('Tiger'),
('Tisch'),('Topf'),('Tor'),('Traum'),('Treppe'),('Trommel'),('Turm'),('Uhr'),('Wache'),('Wal'),
('Wald'),('Wand'),('Wasser'),('Welle'),('Wind'),('Wolf'),('Wolke'),('Wurm'),('Wurst'),('Wüste'),
('Zahn'),('Zaun'),('Zebra'),('Zeitung'),('Zelt'),('Zirkus'),('Zitrone'),('Zug'),('Zwerg'),('Zwiebel'),
('Astronaut'),('Bahnhof'),('Ballon'),('Besen'),('Bibliothek'),('Botschaft'),('Brunnen'),('Clown'),('Code'),('Computer'),
('Detektiv'),('Doktor'),('Echo'),('Eimer'),('Fabrik'),('Fahne'),('Falle'),('Farbe'),('Faust'),('Feld'),
('Fee'),('Fernseher'),('Fieber'),('Friseur'),('Galaxie'),('Gas'),('Gehirn'),('Gespenst'),('Gift'),('Gips'),
('Gleis'),('Griff'),('Hexe'),('Höhle'),('Holz'),('Horn'),('Jagd'),('Juwel'),('Kaktus'),('Kanal'),
('Kanone'),('Keller'),('Kerze'),('Klinge'),('Knochen'),('Kohle'),('Korb'),('Kran'),('Krebs'),('Kreide'),
('Kreis'),('Kreuz'),('Krieg'),('Krokodil'),('Labor'),('Lager'),('Lava'),('Leder'),('Leim'),('Linse'),
('Liste'),('Loch'),('Lotto'),('Lunge'),('Mammut'),('Marmor'),('Maschine'),('Matratze'),('Medizin'),('Mikrofon'),
('Mine'),('Minister'),('Modell'),('Mörder'),('Motte'),('Mumie'),('Muschel'),('Nashorn'),('Natur'),('Ninja'),
('Notar'),('Oase'),('Öl'),('Orden'),('Orgel'),('Orkan'),('Panda'),('Panzer'),('Papagei'),('Paradies'),
('Pass'),('Pause'),('Perle'),('Pfanne'),('Pfeil'),('Pflaster'),('Pinguin'),('Pinsel'),('Platte'),('Pol'),
('Pudding'),('Pulver'),('Punkt'),('Quelle'),('Rahmen'),('Rampe'),('Rätsel'),('Raupe'),('Rede'),('Regal'),
('Reifen'),('Rente'),('Rezept'),('Richter'),('Riff'),('Rinde'),('Rohr'),('Rolle'),('Rost'),('Rubin'),
('Ruder'),('Säge'),('Salat'),('Salz'),('Samen'),('Säule'),('Schach'),('Schal'),('Schale'),('Schaum'),
('Schere'),('Schiene'),('Schirm'),('Schlamm'),('Schlitten'),('Schnur'),('Schraube'),('Schreck'),('Schrift'),('Schritt'),
('Schwamm'),('Schwan'),('Segel'),('Sekunde'),('Silber'),('Sirene'),('Skelett'),('Ski'),('Sofa'),('Soldat'),
('Speck'),('Speer'),('Spitze'),('Sport'),('Spritze'),('Spur'),('Stab'),('Stahl'),('Stamm'),('Staub'),
('Stempel'),('Steuer'),('Stich'),('Stift'),('Stille'),('Stirn'),('Stoff'),('Strahl'),('Streifen'),('Strudel');

-- ---------- Tabu / Alias ----------
insert into public.tabu_words (word, taboo) values
('Geburtstag', '["Kuchen","Kerzen","Feiern","Alter"]'),
('Strand', '["Meer","Sand","Urlaub","Sonne"]'),
('Pizza', '["Italien","Käse","Teig","Belag"]'),
('Fußball', '["Tor","Ball","Spieler","Rasen"]'),
('Kino', '["Film","Popcorn","Leinwand","Ticket"]'),
('Schnee', '["Winter","Kalt","Weiß","Flocken"]'),
('Kaffee', '["Trinken","Koffein","Tasse","Wach"]'),
('Zahnarzt', '["Zähne","Bohrer","Praxis","Schmerzen"]'),
('Flugzeug', '["Fliegen","Pilot","Flughafen","Urlaub"]'),
('Hochzeit', '["Heiraten","Braut","Ring","Kleid"]'),
('Bibliothek', '["Bücher","Leise","Ausleihen","Lesen"]'),
('Gewitter', '["Blitz","Donner","Regen","Wolken"]'),
('Schwimmbad', '["Wasser","Schwimmen","Becken","Rutsche"]'),
('Weihnachten', '["Geschenke","Baum","Dezember","Fest"]'),
('Handy', '["Telefon","Apps","Anrufen","Display"]'),
('Frisör', '["Haare","Schneiden","Schere","Salon"]'),
('Camping', '["Zelt","Natur","Wohnwagen","Übernachten"]'),
('Zirkus', '["Clown","Manege","Zelt","Artisten"]'),
('Supermarkt', '["Einkaufen","Lebensmittel","Kasse","Regal"]'),
('Polizei', '["Verbrecher","Blaulicht","Uniform","Festnehmen"]'),
('Geheimnis', '["Verraten","Wissen","Niemand","Flüstern"]'),
('Pyramide', '["Ägypten","Pharao","Dreieck","Wüste"]'),
('Vampir', '["Blut","Zähne","Knoblauch","Dracula"]'),
('Astronaut', '["Weltall","Rakete","Mond","Anzug"]'),
('Spiegel', '["Sehen","Reflexion","Glas","Bild"]'),
('Honig', '["Bienen","Süß","Brot","Gelb"]'),
('Feuerwehr', '["Löschen","Brand","Schlauch","Rot"]'),
('Schaukel', '["Spielplatz","Hin und her","Kind","Sitzen"]'),
('Regenbogen', '["Farben","Regen","Sonne","Himmel"]'),
('Wecker', '["Aufstehen","Klingeln","Morgens","Uhr"]'),
('Aquarium', '["Fische","Wasser","Glas","Becken"]'),
('Schornstein', '["Rauch","Dach","Kamin","Weihnachtsmann"]'),
('Marathon', '["Laufen","42","Kilometer","Rennen"]'),
('Krankenhaus', '["Arzt","Patient","Operation","Krank"]'),
('Tornado', '["Wind","Wirbel","Sturm","Drehen"]'),
('Pinguin', '["Antarktis","Vogel","Schwarz-weiß","Watscheln"]'),
('Karussell', '["Drehen","Jahrmarkt","Pferde","Fahren"]'),
('Lawine', '["Schnee","Berg","Rutschen","Gefahr"]'),
('Tresor', '["Geld","Sicher","Code","Bank"]'),
('Kompass', '["Norden","Richtung","Nadel","Orientierung"]'),
('Schnorchel', '["Tauchen","Atmen","Wasser","Rohr"]'),
('Murmeltier', '["Tier","Schlafen","Berg","Pfeifen"]'),
('Achterbahn', '["Freizeitpark","Schnell","Looping","Fahren"]'),
('Bumerang', '["Werfen","Zurück","Australien","Holz"]'),
('Iglu', '["Eis","Eskimo","Haus","Schnee"]'),
('Vulkan', '["Lava","Ausbruch","Berg","Feuer"]'),
('Tastatur', '["Computer","Tippen","Tasten","Schreiben"]'),
('Gondel', '["Venedig","Boot","Kanal","Seilbahn"]'),
('Mikrowelle', '["Erwärmen","Essen","Küche","Strahlen"]'),
('Sanduhr', '["Zeit","Rieseln","Glas","Umdrehen"]'),
('Leuchtturm', '["Meer","Licht","Schiffe","Küste"]'),
('Trampolin', '["Springen","Hüpfen","Garten","Hoch"]'),
('Werwolf', '["Vollmond","Verwandlung","Wolf","Mensch"]'),
('Oktopus', '["Acht","Arme","Meer","Tinte"]'),
('Limonade', '["Trinken","Süß","Zitrone","Sprudel"]'),
('Mülleimer', '["Abfall","Wegwerfen","Tonne","Deckel"]'),
('Fallschirm', '["Springen","Flugzeug","Schweben","Landen"]'),
('Klavier', '["Tasten","Musik","Spielen","Instrument"]'),
('Wüste', '["Sand","Heiß","Kamel","Trocken"]'),
('Pirat', '["Schiff","Schatz","Augenklappe","Meer"]'),
('Gips', '["Bruch","Arm","Weiß","Unterschreiben"]'),
('Magnet', '["Anziehen","Eisen","Pol","Kühlschrank"]'),
('Stau', '["Autos","Autobahn","Warten","Verkehr"]'),
('Heißluftballon', '["Fliegen","Korb","Feuer","Himmel"]'),
('Schiedsrichter', '["Pfeife","Spiel","Karte","Entscheiden"]'),
('Zelt', '["Camping","Schlafen","Aufbauen","Stoff"]'),
('Lagerfeuer', '["Brennen","Stockbrot","Holz","Camping"]'),
('U-Boot', '["Tauchen","Wasser","Militär","Tief"]'),
('Geldautomat', '["Abheben","Karte","Bank","PIN"]'),
('Sternschnuppe', '["Wunsch","Himmel","Fallen","Nacht"]'),
('Massage', '["Rücken","Entspannen","Hände","Wellness"]'),
('Pfandflasche', '["Automat","Zurückbringen","Geld","Leer"]'),
('Grillen', '["Sommer","Fleisch","Kohle","Garten"]'),
('Karaoke', '["Singen","Mikrofon","Text","Bar"]'),
('Schluckauf', '["Hicks","Erschrecken","Luft","Zwerchfell"]'),
('Picknick', '["Decke","Essen","Park","Korb"]'),
('Aufzug', '["Fahren","Stockwerk","Knopf","Hoch"]'),
('Tatort', '["Krimi","Sonntag","Fernsehen","Kommissar"]'),
('Flohmarkt', '["Verkaufen","Gebraucht","Stand","Handeln"]'),
('Spülmaschine', '["Geschirr","Sauber","Küche","Tabs"]'),
('Sonnenbrand', '["Rot","Haut","Creme","Sommer"]'),
('Jetlag', '["Zeitverschiebung","Müde","Fliegen","Reise"]'),
('Maulwurf', '["Graben","Hügel","Blind","Garten"]'),
('Currywurst', '["Imbiss","Pommes","Soße","Berlin"]'),
('Däumchen', '["Drehen","Langeweile","Finger","Warten"]'),
('Eichhörnchen', '["Nüsse","Baum","Buschig","Sammeln"]'),
('Doppelgänger', '["Ähnlich","Aussehen","Zwilling","Verwechseln"]'),
('Föhn', '["Haare","Trocknen","Heiß","Luft"]'),
('Hängematte', '["Liegen","Bäume","Schaukeln","Entspannen"]'),
('Kronkorken', '["Flasche","Öffnen","Bier","Metall"]'),
('Ohrwurm', '["Lied","Kopf","Melodie","Nicht loswerden"]'),
('Praktikum', '["Arbeit","Erfahrung","Unbezahlt","Student"]'),
('Quietscheente', '["Badewanne","Gelb","Gummi","Wasser"]'),
('Rolltreppe', '["Stufen","Fahren","Kaufhaus","Stehen"]'),
('Schneemann', '["Winter","Karotte","Bauen","Kugeln"]'),
('Selfie', '["Foto","Handy","Selbst","Kamera"]'),
('Streich', '["April","Reinlegen","Lachen","Opfer"]'),
('Taschenlampe', '["Licht","Dunkel","Batterie","Leuchten"]'),
('Umzug', '["Kartons","Wohnung","Möbel","Tragen"]'),
('Verspätung', '["Zug","Warten","Bahn","Zu spät"]'),
('Wattestäbchen', '["Ohren","Reinigen","Weiß","Klein"]'),
('Zeitmaschine', '["Reisen","Vergangenheit","Zukunft","Erfinden"]'),
('Abseits', '["Fußball","Regel","Schiedsrichter","Position"]'),
('Bart', '["Rasieren","Gesicht","Haare","Mann"]'),
('Casting', '["Show","Bewerben","Jury","Talent"]'),
('Dialekt', '["Sprechen","Region","Bayern","Akzent"]'),
('Einhorn', '["Horn","Pferd","Regenbogen","Fabelwesen"]'),
('Fernbedienung', '["Fernseher","Knöpfe","Zappen","Suchen"]'),
('Geisterbahn', '["Jahrmarkt","Gruseln","Fahren","Erschrecken"]'),
('Hausarrest', '["Strafe","Zuhause","Eltern","Verbot"]'),
('Inventur', '["Zählen","Lager","Geschäft","Liste"]'),
('Jackpot', '["Lotto","Gewinnen","Millionen","Glück"]'),
('Kaugummi', '["Kauen","Blase","Süß","Kleben"]'),
('Lampenfieber', '["Bühne","Nervös","Auftritt","Angst"]'),
('Muskelkater', '["Sport","Schmerzen","Training","Danach"]'),
('Nachtschicht', '["Arbeiten","Dunkel","Müde","Schlafen"]'),
('Orchester', '["Musik","Dirigent","Instrumente","Konzert"]'),
('Pantomime', '["Stumm","Zeigen","Gesten","Raten"]'),
('Quarantäne', '["Krank","Isolation","Zuhause","Ansteckend"]'),
('Rückspiegel', '["Auto","Schauen","Hinten","Glas"]'),
('Stundenplan', '["Schule","Fächer","Woche","Unterricht"]'),
('Trinkgeld', '["Kellner","Geben","Restaurant","Extra"]'),
('Wimpernkleber', '["Augen","Beauty","Künstlich","Schminken"]'),
('WG', '["Wohnen","Mitbewohner","Teilen","Zimmer"]'),
('Föhnfrisur', '["Haare","Stylen","Volumen","Trocknen"]'),
('Bauchgefühl', '["Intuition","Entscheiden","Spüren","Ahnung"]');
