-- Seed: Wer bin ich?, Custom Bingo, Hot Takes, Ranking Battle, Gartic Phone, Blind Test

-- ---------- Wer bin ich? ----------
insert into public.whoami_characters (name, category) values
('Albert Einstein','Geschichte'),('Kleopatra','Geschichte'),('Leonardo da Vinci','Geschichte'),('Napoleon','Geschichte'),
('Mozart','Geschichte'),('Königin Elisabeth II.','Geschichte'),('Mahatma Gandhi','Geschichte'),('Martin Luther King','Geschichte'),
('Christoph Kolumbus','Geschichte'),('Marie Curie','Geschichte'),('Beethoven','Geschichte'),('Anne Frank','Geschichte'),
('Julius Cäsar','Geschichte'),('Abraham Lincoln','Geschichte'),('Nelson Mandela','Geschichte'),('Frida Kahlo','Geschichte'),
('Micky Maus','Cartoon'),('SpongeBob','Cartoon'),('Homer Simpson','Cartoon'),('Pikachu','Cartoon'),
('Donald Duck','Cartoon'),('Bart Simpson','Cartoon'),('Shrek','Film'),('Elsa','Film'),
('Tom (Tom & Jerry)','Cartoon'),('Garfield','Cartoon'),('Asterix','Comic'),('Obelix','Comic'),
('Tim (Tim & Struppi)','Comic'),('Lucky Luke','Comic'),('Spiderman','Comic'),('Batman','Comic'),
('Superman','Comic'),('Wonder Woman','Comic'),('Hulk','Comic'),('Iron Man','Comic'),
('Harry Potter','Film'),('Hermine Granger','Film'),('Dumbledore','Film'),('Voldemort','Film'),
('Gandalf','Film'),('Frodo','Film'),('Gollum','Film'),('Darth Vader','Film'),
('Yoda','Film'),('Luke Skywalker','Film'),('James Bond','Film'),('Indiana Jones','Film'),
('Jack Sparrow','Film'),('Forrest Gump','Film'),('Rocky Balboa','Film'),('Terminator','Film'),
('E.T.','Film'),('King Kong','Film'),('Godzilla','Film'),('Mary Poppins','Film'),
('Willy Wonka','Film'),('Joker','Film'),('Harley Quinn','Film'),('Katniss Everdeen','Film'),
('Sherlock Holmes','Literatur'),('Pippi Langstrumpf','Literatur'),('Robin Hood','Literatur'),('Dracula','Literatur'),
('Frankensteins Monster','Literatur'),('Romeo','Literatur'),('Rapunzel','Märchen'),('Aschenputtel','Märchen'),
('Schneewittchen','Märchen'),('Rotkäppchen','Märchen'),('Der gestiefelte Kater','Märchen'),('Pinocchio','Märchen'),
('Peter Pan','Märchen'),('Aladdin','Märchen'),('Arielle','Film'),('Simba','Film'),
('Nemo','Film'),('Buzz Lightyear','Film'),('Woody','Film'),('Olaf (Frozen)','Film'),
('Minion','Film'),('Kung Fu Panda','Film'),('Mufasa','Film'),('Tarzan','Film'),
('Hercules','Mythologie'),('Zeus','Mythologie'),('Poseidon','Mythologie'),('Medusa','Mythologie'),
('Thor','Mythologie'),('Loki','Mythologie'),('Achilles','Mythologie'),('Odysseus','Mythologie'),
('Cristiano Ronaldo','Sport'),('Lionel Messi','Sport'),('Michael Jordan','Sport'),('Serena Williams','Sport'),
('Usain Bolt','Sport'),('Muhammad Ali','Sport'),('Manuel Neuer','Sport'),('Lewis Hamilton','Sport'),
('Michael Schumacher','Sport'),('Dirk Nowitzki','Sport'),('Roger Federer','Sport'),('Mike Tyson','Sport'),
('Michael Jackson','Musik'),('Elvis Presley','Musik'),('Madonna','Musik'),('Beyoncé','Musik'),
('Taylor Swift','Musik'),('Ed Sheeran','Musik'),('Adele','Musik'),('Rihanna','Musik'),
('Eminem','Musik'),('Snoop Dogg','Musik'),('Lady Gaga','Musik'),('Freddie Mercury','Musik'),
('Billie Eilish','Musik'),('Helene Fischer','Musik'),('Udo Lindenberg','Musik'),('Apache 207','Musik'),
('Capital Bra','Musik'),('Shirin David','Musik'),('Bushido','Musik'),('Nina Chuba','Musik'),
('Angela Merkel','Politik'),('Barack Obama','Politik'),('Donald Trump','Politik'),('Wladimir Putin','Politik'),
('Olaf Scholz','Politik'),('Emmanuel Macron','Politik'),('Wolodymyr Selenskyj','Politik'),('Boris Johnson','Politik'),
('Elon Musk','Wirtschaft'),('Bill Gates','Wirtschaft'),('Mark Zuckerberg','Wirtschaft'),('Jeff Bezos','Wirtschaft'),
('Steve Jobs','Wirtschaft'),('Kim Kardashian','Promi'),('Heidi Klum','Promi'),('Dieter Bohlen','Promi'),
('Stefan Raab','Promi'),('Günther Jauch','Promi'),('Joko Winterscheidt','Promi'),('Klaas Heufer-Umlauf','Promi'),
('Leonardo DiCaprio','Promi'),('Brad Pitt','Promi'),('Angelina Jolie','Promi'),('Johnny Depp','Promi'),
('Will Smith','Promi'),('Dwayne Johnson','Promi'),('Keanu Reeves','Promi'),('Emma Watson','Promi'),
('Ryan Reynolds','Promi'),('Tom Cruise','Promi'),('Jennifer Lawrence','Promi'),('Zendaya','Promi'),
('Mario','Videospiel'),('Luigi','Videospiel'),('Princess Peach','Videospiel'),('Sonic','Videospiel'),
('Lara Croft','Videospiel'),('Link (Zelda)','Videospiel'),('Kratos','Videospiel'),('Pac-Man','Videospiel'),
('Der Weihnachtsmann','Fantasie'),('Der Osterhase','Fantasie'),('Die Zahnfee','Fantasie'),('Ein Zombie','Fantasie'),
('Ein Alien','Fantasie'),('Ein Werwolf','Fantasie'),('Eine Meerjungfrau','Fantasie'),('Ein Roboter','Fantasie');

-- ---------- Custom Bingo (Füll-Statements) ----------
insert into public.bingo_statements (text) values
('Jemand verschüttet ein Getränk'),
('Jemand erzählt eine Geschichte zum dritten Mal'),
('Jemand schaut länger als 2 Minuten aufs Handy'),
('Zwei Leute reden gleichzeitig los'),
('Jemand sagt "nur noch eine Runde"'),
('Jemand muss das Spiel erklärt bekommen'),
('Jemand lacht über den eigenen Witz'),
('Jemand holt Snacks'),
('Jemand zitiert ein Meme'),
('Jemand sagt "das war schon immer so"'),
('Jemand gähnt vor Mitternacht'),
('Jemand beschwert sich über die Regeln'),
('Jemand macht ein Foto für die Story'),
('Jemand singt plötzlich los'),
('Jemand erwähnt seine Arbeit / die Uni / die Schule'),
('Jemand sagt "Moment, ich muss kurz…"'),
('Jemand fragt nach dem WLAN-Passwort'),
('Jemand verliert und behauptet, das Spiel sei unfair'),
('Jemand bekommt einen Lachanfall'),
('Jemand redet über Essen, während alle essen'),
('Jemand erwähnt eine Ex / einen Ex'),
('Jemand will die Musik wechseln'),
('Jemand sagt einen Satz auf Englisch'),
('Jemand erzählt einen Flachwitz'),
('Jemand steht auf und vergisst, warum'),
('Jemand checkt heimlich die Uhrzeit'),
('Jemand sagt "ich hab'' euch das doch erzählt, oder?"'),
('Jemand verwechselt zwei Namen'),
('Jemand stößt mit dem Knie/Ellbogen irgendwo an'),
('Jemand droht im Spaß mit Heimgehen'),
('Jemand schlägt ein neues Spiel vor, bevor das alte fertig ist'),
('Jemand sagt "kurze Frage" und stellt drei'),
('Jemand erwähnt das Wetter'),
('Jemand will unbedingt Teams neu mischen'),
('Jemand isst das letzte Stück von etwas'),
('Jemand macht eine dramatische Pause beim Erzählen'),
('Jemand sagt "ohne Kontext klingt das komisch"'),
('Jemand niest mehr als zweimal hintereinander'),
('Jemand spricht in einem schlechten Akzent'),
('Jemand verteidigt eine unpopuläre Meinung'),
('Jemand fängt einen Satz an und beendet ihn nie'),
('Jemand benutzt das Wort "wild"'),
('Jemand schlägt vor, Pizza zu bestellen'),
('Jemand vergleicht etwas mit einer Serie'),
('Jemand sagt "bin gleich wieder da" und bleibt 10 Minuten weg'),
('Jemand spielt mit seinem Glas/seiner Flasche herum'),
('Jemand will einen Gruppenchat-Screenshot zeigen'),
('Jemand erklärt etwas mit Händen und Füßen'),
('Jemand summt einen Ohrwurm'),
('Jemand sagt "Leute, mal ganz ehrlich…"'),
('Jemand beginnt eine Geschichte mit "Kennt ihr das, wenn…"'),
('Jemand muss aufs Klo, sobald die Runde startet'),
('Jemand zeigt ein Tiervideo'),
('Jemand sagt "Ich bin zu alt für sowas"'),
('Jemand korrigiert die Aussprache von jemandem'),
('Jemand prahlt mit einem alten Erfolg'),
('Jemand verliert den Faden mitten im Satz'),
('Jemand schaut bei einer Frage zum Partner/zur besten Freundin'),
('Jemand fragt, wie spät es ist, obwohl er eine Uhr trägt'),
('Jemand sagt "das machen wir nächstes Mal besser"'),
('Jemand erschrickt sich grundlos'),
('Jemand redet mit vollem Mund weiter'),
('Jemand erwähnt sein Sternzeichen'),
('Jemand sagt "Ich hab Hunger", obwohl gerade gegessen wurde'),
('Jemand stellt eine hypothetische Frage, die eskaliert'),
('Jemand klatscht beim Lachen'),
('Jemand sagt "noch 5 Minuten, dann geh ich"'),
('Jemand vergisst, dass er an der Reihe ist'),
('Jemand findet sein Handy nicht, obwohl er draufsitzt'),
('Jemand fragt "Worum ging''s nochmal?"'),
('Jemand will ein Gruppenfoto machen'),
('Jemand kann sich nicht entscheiden'),
('Jemand spoilert fast eine Serie'),
('Jemand benutzt eine Floskel der Eltern'),
('Jemand erzählt von einem Traum'),
('Jemand sagt "Das könnte ein Podcast sein"'),
('Jemand fängt an aufzuräumen, obwohl niemand geht'),
('Jemand schlägt eine Wette vor'),
('Jemand sucht ein bestimmtes Lied länger als 2 Minuten'),
('Jemand redet über früher, als wäre es Jahrzehnte her'),
('Jemand verschickt eine Sprachnachricht'),
('Jemand zieht die Schuhe aus'),
('Jemand sagt "Ich hab eine Theorie…"');

-- ---------- Hot Takes / Quiplash-Style ----------
insert into public.hottake_prompts (text) values
('Der schlechteste Name für ein Haustier wäre…'),
('Was steht ganz unten auf deiner Bucket List?'),
('Der schlimmste Satz, den man beim ersten Date sagen kann:'),
('Ein Filmtitel, der dein Leben beschreibt:'),
('Der unnötigste Superheld der Welt hätte diese Superkraft:'),
('Was wäre der schlechteste Slogan für eine Zahnarztpraxis?'),
('Der wahre Grund, warum Dinosaurier ausgestorben sind:'),
('Was würde deine Suchhistorie der Polizei verraten?'),
('Der schlechteste Name für ein Restaurant:'),
('Was wäre das Schlimmste, das man in einer Hochzeitsrede sagen könnte?'),
('Ein Produkt, das niemand braucht, aber jeder kaufen würde:'),
('Der peinlichste Klingelton für ein Vorstellungsgespräch:'),
('Was sagt man besser NICHT zum Friseur?'),
('Die schlechteste neue Eissorte:'),
('Was wäre der schlimmste Pflichtkurs in der Schule?'),
('Ein Geheimnis, das Lehrer vor Schülern verbergen:'),
('Der wahre Grund, warum das WLAN langsam ist:'),
('Was steht im Kleingedruckten eines Paktes mit dem Teufel?'),
('Die schlechteste Anmachzeile aller Zeiten:'),
('Was wäre ein furchtbarer Name für ein Parfüm?'),
('Wofür sollte es einen Nobelpreis geben, den es noch nicht gibt?'),
('Was würde dein Haustier über dich aussagen, wenn es reden könnte?'),
('Der schlechteste Ratschlag, den man einem Kind geben kann:'),
('Was wäre die nervigste Superkraft überhaupt?'),
('Ein Satz, den man nie vom Piloten hören will:'),
('Was wäre der schlimmste Geschmack für Zahnpasta?'),
('Der wahre Inhalt der Area 51:'),
('Was würdest du mit deinem letzten Tag auf der Erde anfangen?'),
('Die schlechteste Idee für eine Reality-Show:'),
('Was sollte man niemals googeln?'),
('Ein Satz, den man nie vom Chirurgen hören will:'),
('Was wäre das schlechteste Werbegeschenk einer Bank?'),
('Der schlimmste Ort für ein erstes Date:'),
('Was machen Lehrer wirklich im Lehrerzimmer?'),
('Eine Regel, die es in jeder WG geben sollte:'),
('Der schlechteste Text für eine Grußkarte:'),
('Was wäre der furchtbarste Jingle für eine Beerdigungsfirma?'),
('Wenn Montage eine Person wären, dann…'),
('Was ist die wahre Bedeutung von "AGB gelesen und akzeptiert"?'),
('Der schlechteste Name für eine Boyband:'),
('Was würde auf deinem Grabstein stehen, wenn deine Freunde entscheiden?'),
('Eine Sache, die in keiner Zombie-Apokalypse fehlen darf:'),
('Was wäre die schlechteste Sportart bei Olympia?'),
('Der wahre Grund, warum Aliens die Erde nicht besuchen:'),
('Was wäre ein schrecklicher Name für ein Krankenhaus?'),
('Die nutzloseste App, die du dir vorstellen kannst:'),
('Was sagt niemand laut, aber alle denken es?'),
('Das Peinlichste, was auf einem Konzert passieren kann:'),
('Wie würde dein Leben als Netflix-Serie heißen?'),
('Was wäre die schlimmste Pizzasorte?'),
('Ein Gesetz, das du sofort einführen würdest:'),
('Was war der eigentliche Plan B von Noah ohne Arche?'),
('Der schlechteste Zeitpunkt für einen Lachanfall:'),
('Was würdest du tun, wenn du einen Tag Bürgermeister wärst?'),
('Die schlechteste Eröffnung für eine Abschlussrede:'),
('Was wäre das nervigste Feature für ein neues Smartphone?'),
('Ein Buchtitel, den niemand kaufen würde:'),
('Was wäre der schlimmste Sponsor für eine Schule?'),
('Wie beendet man ein Telefonat mit Oma in unter 30 Minuten?'),
('Was würde passieren, wenn Tiere einen Tag sprechen könnten?'),
('Der schlechteste Beruf für jemanden mit Lampenfieber:'),
('Was wäre die schlechteste Funktion für einen Smart-Kühlschrank?'),
('Ein Motto, das niemand auf ein T-Shirt drucken sollte:'),
('Was wäre der schlimmste Ohrwurm, um damit aufzuwachen?'),
('Die ehrlichste Stellenanzeige der Welt würde sagen:'),
('Was wäre das schlechteste Thema für einen Podcast?'),
('Wofür würdest du 100 Euro ausgeben, ohne es je zuzugeben?'),
('Was wäre der schlechteste Name für ein Fitnessstudio?'),
('Ein Satz, mit dem man jede Party sofort beendet:'),
('Was würde ein Toaster denken, wenn er denken könnte?'),
('Die schlechteste Ausrede für Zuspätkommen:'),
('Was wäre das schlimmste Hochzeitsgeschenk?'),
('Welcher Beruf bräuchte dringend eine eigene Doku-Soap?'),
('Was wäre der ungeeignetste Song für einen Hochzeitstanz?'),
('Ein neuer Feiertag, den Deutschland braucht:'),
('Was wäre die schlechteste Berufung für ein Horoskop?'),
('Wie würde die Welt aussehen, wenn Kinder regieren würden?'),
('Was wäre das schlechteste Mitbringsel für ein Abendessen bei den Schwiegereltern?'),
('Der schlimmste Satz mitten im Horrorfilm-Marathon:'),
('Was wäre die absurdeste Weltrekord-Kategorie?'),
('Ein Schulfach, das dich aufs echte Leben vorbereitet hätte:'),
('Was würde dein 10-jähriges Ich zu deinem Leben sagen?'),
('Der schlechteste Ort, um sein Handy zu vergessen:'),
('Was wäre der furchtbarste Duft für eine Duftkerze?');

-- ---------- Ranking Battle ----------
insert into public.ranking_prompts (text) values
('Wer würde am ehesten eine Zombie-Apokalypse überleben?'),
('Wer würde am ehesten berühmt werden?'),
('Wer verschläft am ehesten einen wichtigen Termin?'),
('Wer würde am ehesten im Lotto gewinnen und alles verprassen?'),
('Wer würde am ehesten bei einer Quizshow gewinnen?'),
('Wer würde am ehesten ein Restaurant eröffnen?'),
('Wer weint am ehesten bei einem Film?'),
('Wer würde am ehesten spontan auswandern?'),
('Wer hat am ehesten 100 ungelesene Nachrichten?'),
('Wer würde am ehesten Promi-Big-Brother gewinnen?'),
('Wer kommt am ehesten zu spät zur eigenen Hochzeit?'),
('Wer würde am ehesten ein Start-up gründen?'),
('Wer würde am ehesten beim Karaoke das Mikrofon nicht mehr abgeben?'),
('Wer überlebt am längsten ohne Handy?'),
('Wer würde am ehesten mit einem Tier sprechen wollen?'),
('Wer gibt am ehesten sein letztes Geld für Essen aus?'),
('Wer würde am ehesten einen Marathon laufen?'),
('Wer würde am ehesten heimlich in einer Reality-Show mitmachen?'),
('Wer hat die meisten Tabs im Browser offen?'),
('Wer würde am ehesten Politiker werden?'),
('Wer würde am ehesten sein Handy in der Toilette versenken?'),
('Wer lacht am ehesten an unpassenden Stellen?'),
('Wer würde am ehesten vergessen, wo das Auto geparkt ist?'),
('Wer würde am ehesten einen Foodblog starten?'),
('Wer kann am besten Geheimnisse bewahren?'),
('Wer würde am ehesten in einem Escape Room in Panik geraten?'),
('Wer würde am ehesten Influencer werden?'),
('Wer ist am ehesten der Mama-/Papa-Typ der Gruppe?'),
('Wer würde am ehesten bei "Wer wird Millionär" den Publikumsjoker verschwenden?'),
('Wer geht am ehesten als Erstes von einer Party?'),
('Wer bleibt am ehesten bis zum Schluss auf einer Party?'),
('Wer würde am ehesten ein Instrument lernen und nach 2 Wochen aufgeben?'),
('Wer hat am ehesten einen geheimen Zweit-Account?'),
('Wer würde am ehesten beim Camping nach einer Nacht aufgeben?'),
('Wer würde am ehesten versehentlich auf "Allen antworten" drücken?'),
('Wer würde am ehesten ein Buch schreiben?'),
('Wer würde am ehesten einen Preis für Pünktlichkeit gewinnen?'),
('Wer würde am ehesten sein WLAN-Passwort nicht auswendig kennen?'),
('Wer würde am ehesten beim ersten Date über die Ex reden?'),
('Wer würde am ehesten eine Pflanze am Leben erhalten?'),
('Wer würde am ehesten vergessen, dass der Ofen an ist?'),
('Wer hat den chaotischsten Kleiderschrank?'),
('Wer würde am ehesten bei einer Kochshow rausfliegen?'),
('Wer würde am ehesten heimlich tanzen, wenn niemand zusieht?'),
('Wer würde am ehesten ein Tattoo spontan stechen lassen?'),
('Wer würde am ehesten alle Geburtstage vergessen?'),
('Wer würde am ehesten Lehrer werden?'),
('Wer würde am ehesten beim Monopoly den Tisch umwerfen?'),
('Wer hat am ehesten Angst vor Spinnen?'),
('Wer würde am ehesten ein Wochenende komplett durchschlafen?'),
('Wer würde am ehesten als Detektiv arbeiten?'),
('Wer würde am ehesten beim Schwarzfahren erwischt werden?'),
('Wer würde am ehesten versehentlich in den falschen Zug steigen?'),
('Wer würde am ehesten einen Podcast starten?'),
('Wer würde am ehesten beim Wandern die Gruppe verlaufen lassen?'),
('Wer würde am ehesten in einer Talentshow auftreten?'),
('Wer würde am ehesten eine überraschende verborgene Begabung enthüllen?'),
('Wer würde am ehesten sein Essen fotografieren, bevor es kalt wird?'),
('Wer würde am ehesten im Urlaub nur am Pool liegen?'),
('Wer würde am ehesten den Klimaanlagen-Krieg im Büro starten?'),
('Wer würde am ehesten freiwillig zur Mond-Mission aufbrechen?'),
('Wer würde am ehesten beim Aufbau von IKEA-Möbeln verzweifeln?'),
('Wer würde am ehesten ein eigenes Brettspiel erfinden?'),
('Wer würde am ehesten die Gruppe im Gruppenchat stummschalten?'),
('Wer würde am ehesten bei einem Horrorfilm die Augen zuhalten?'),
('Wer würde am ehesten sein Passwort überall gleich benutzen?'),
('Wer würde am ehesten aus Versehen berühmt werden?'),
('Wer würde am ehesten beim Flunkyball gewinnen?'),
('Wer würde am ehesten nachts um 3 philosophische Fragen stellen?'),
('Wer würde am ehesten den Kühlschrank um Mitternacht plündern?'),
('Wer würde am ehesten zwei Wochen ohne Social Media aushalten?'),
('Wer würde am ehesten beim Versteckspiel als Erstes gefunden?'),
('Wer würde am ehesten versehentlich eine Sprachnachricht von 10 Minuten schicken?'),
('Wer würde am ehesten in einer Band spielen?'),
('Wer würde am ehesten ein Haustier nach einem Essen benennen?');

-- ---------- Gartic Phone Start-Prompts ----------
insert into public.gartic_prompts (text) values
('Ein Pinguin im Fitnessstudio'),
('Oma fährt Skateboard'),
('Ein Hai im Schwimmreifen'),
('Aliens beim Grillen'),
('Eine Katze als Anwältin'),
('Ein Dinosaurier im Supermarkt'),
('Der Weihnachtsmann am Strand'),
('Ein Roboter verliebt sich in einen Toaster'),
('Ein Einhorn im Stau'),
('Ein Astronaut beim Pizzabacken'),
('Ein Vampir beim Zahnarzt'),
('Eine Giraffe in der U-Bahn'),
('Ein Zauberer verliert seinen Hut'),
('Ein Hund führt ein Meeting'),
('Eine Banane macht Yoga'),
('Ein Geist beim Friseur'),
('Ein Drache backt Kekse'),
('Ein Pirat sucht sein WLAN'),
('Eine Schildkröte gewinnt ein Wettrennen'),
('Ein Clown im Bewerbungsgespräch'),
('Ein Faultier beim Marathon'),
('Eine Hexe im Supermarkt-Sonderangebot'),
('Ein Oktopus beim Jonglieren'),
('Ein Ritter mit Rückenschmerzen'),
('Eine Ameise zieht um'),
('Ein Bär bestellt Kaffee'),
('Ein UFO an der Tankstelle'),
('Eine Meerjungfrau im Schwimmkurs'),
('Ein Krokodil im Ballettkurs'),
('Ein Hamster plant die Weltherrschaft'),
('Ein Schneemann im Sommerurlaub'),
('Ein Frosch wartet auf seinen Kuss'),
('Ein Zombie beim Frühstück'),
('Eine Kuh auf dem Mond'),
('Ein Papagei verrät alle Geheimnisse'),
('Ein Wal in der Badewanne'),
('Ein Igel beim Luftballon-Verkauf'),
('Ein Kaktus sucht eine Umarmung'),
('Ein Eichhörnchen vergisst sein Versteck'),
('Ein Löwe beim Friseur'),
('Eine Ente im Anzug'),
('Ein Gespenst hat Angst im Dunkeln'),
('Ein Koch kämpft gegen eine riesige Nudel'),
('Ein Fisch lernt Fahrradfahren'),
('Die Zahnfee im Streik'),
('Ein Riese in einem winzigen Haus'),
('Ein Pilz auf Weltreise'),
('Eine Wolke mit schlechter Laune'),
('Ein Stier im Porzellanladen'),
('Ein Detektiv verfolgt eine Schnecke'),
('Ein Berg besteigt einen Menschen'),
('Eine Pizza bestellt einen Menschen'),
('Ein Skelett im Sonnenstudio'),
('Ein Pinsel malt sich selbst'),
('Ein Magier sägt sein Publikum in der Mitte durch... vor Langeweile'),
('Ein Flamingo auf Stelzen'),
('Ein Maulwurf mit Sonnenbrille'),
('Eine Rakete mit Flugangst'),
('Ein Spiegel, der Komplimente macht'),
('Ein Toast springt zu hoch'),
('Eine Sockenpuppe übernimmt die Regierung'),
('Ein Kraken-DJ legt auf'),
('Ein Lama spuckt Konfetti'),
('Eine Schnecke mit Raketenantrieb'),
('Ein Waschbär räumt auf, statt zu klauen'),
('Ein Adler mit Höhenangst'),
('Ein Brokkoli auf einer Party voller Süßigkeiten'),
('Ein Yeti beim Sonnenbaden'),
('Eine Qualle als Lampenschirm'),
('Ein Pferd im Homeoffice'),
('Ein Keks wehrt sich gegen das Eintunken'),
('Eine Ananas auf einer Pizza-Demo'),
('Ein Roboter mit Schluckauf'),
('Ein Specht mit Kopfschmerzen'),
('Ein Gnu im Wartezimmer'),
('Ein Chamäleon, das sich nicht entscheiden kann'),
('Ein Murmeltier verschläft den Murmeltiertag'),
('Ein Leuchtturm mit ausgebrannter Birne'),
('Eine Avocado sucht ihre andere Hälfte'),
('Ein Kühlschrank läuft weg'),
('Eine Karotte beim Augenarzt'),
('Ein Bagger im Sandkasten-Wettbewerb'),
('Eine Biene im Anflug auf ein Gummibärchen'),
('Ein Anglerfisch mit Energiesparlampe');

-- ---------- Blind Test Song-Pool (Host sucht den Song auf YouTube) ----------
insert into public.blindtest_songs (title, artist, category) values
('Bohemian Rhapsody','Queen','Rock-Klassiker'),
('Billie Jean','Michael Jackson','Pop-Klassiker'),
('Smells Like Teen Spirit','Nirvana','Rock-Klassiker'),
('Wonderwall','Oasis','Rock-Klassiker'),
('Take On Me','a-ha','80er'),
('Africa','Toto','80er'),
('Sweet Child O'' Mine','Guns N'' Roses','Rock-Klassiker'),
('Like a Prayer','Madonna','80er'),
('I Want It That Way','Backstreet Boys','90er'),
('...Baby One More Time','Britney Spears','90er'),
('Wannabe','Spice Girls','90er'),
('No Scrubs','TLC','90er'),
('Lose Yourself','Eminem','Hip-Hop'),
('In Da Club','50 Cent','Hip-Hop'),
('Empire State of Mind','Jay-Z feat. Alicia Keys','Hip-Hop'),
('Hey Ya!','OutKast','2000er'),
('Crazy In Love','Beyoncé','2000er'),
('Umbrella','Rihanna','2000er'),
('Viva La Vida','Coldplay','2000er'),
('Mr. Brightside','The Killers','2000er'),
('Rolling in the Deep','Adele','2010er'),
('Uptown Funk','Mark Ronson feat. Bruno Mars','2010er'),
('Shape of You','Ed Sheeran','2010er'),
('Blinding Lights','The Weeknd','2010er'),
('Bad Guy','Billie Eilish','2010er'),
('Shake It Off','Taylor Swift','2010er'),
('Happy','Pharrell Williams','2010er'),
('Get Lucky','Daft Punk','2010er'),
('Levitating','Dua Lipa','2020er'),
('As It Was','Harry Styles','2020er'),
('Flowers','Miley Cyrus','2020er'),
('99 Luftballons','Nena','Deutsch'),
('Atemlos durch die Nacht','Helene Fischer','Deutsch'),
('Männer','Herbert Grönemeyer','Deutsch'),
('Du hast','Rammstein','Deutsch'),
('Auf uns','Andreas Bourani','Deutsch'),
('Lieder','Adel Tawil','Deutsch'),
('80 Millionen','Max Giesinger','Deutsch'),
('Roller','Apache 207','Deutschrap'),
('110','Capital Bra & Samra','Deutschrap'),
('Wildberry Lillet','Nina Chuba','Deutschrap'),
('Ohne mein Team','Bonez MC & RAF Camora','Deutschrap'),
('Cordula Grün','Josh.','Party'),
('Macarena','Los del Río','Party'),
('Despacito','Luis Fonsi','Party'),
('Gangnam Style','PSY','Party'),
('Last Christmas','Wham!','Weihnachten'),
('All I Want for Christmas Is You','Mariah Carey','Weihnachten'),
('Dance Monkey','Tones and I','2010er'),
('Someone Like You','Adele','Ballade'),
('Let It Go','Idina Menzel (Frozen)','Film'),
('My Heart Will Go On','Céline Dion','Film'),
('Eye of the Tiger','Survivor','Film'),
('Ghostbusters','Ray Parker Jr.','Film'),
('Smoke on the Water','Deep Purple','Rock-Klassiker'),
('Highway to Hell','AC/DC','Rock-Klassiker'),
('Stayin'' Alive','Bee Gees','Disco'),
('Dancing Queen','ABBA','Disco'),
('I Will Survive','Gloria Gaynor','Disco'),
('Super Trouper','ABBA','Disco');
